Feature/business signup
BCSDLab/KOIN_ANDROID pull request #203
Opened 2024-03-30 07:25 UTC by skdud0629

### **회원가입**

- 화면 ui 생성

### **TODO**

- navtigation 구현

2024-03-31 16:32 UTC, yunjaena reviewed
수고했습니다 :) 커맨트 확인해주세요!

2024-03-31 16:32 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/accountauth/AccountAuthScreen.kt
> +
빈 공간 제거 해주세요~!

2024-03-31 16:32 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/accountauth/AccountAuthScreen.kt
> +                    color = Color(0xFFF7941E),
Color를 직접 넣으시면 변경하기 어렵습니다. Compose Color 시스템을 알아보는게 좋아보입니다.

2024-03-31 16:32 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/BusinessAuthScreen.kt
> +    val itemList: MutableList<String> = mutableListOf()
상태 호이스팅에 대해서 알아보면 좋을것 같습니다.

2024-03-31 16:32 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/BusinessAuthScreen.kt
> +                fontWeight = Bold,
Compose theme에 대해서 알아보면 좋을것 같습니다 :)

2024-03-31 16:32 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +    var isButtonClicked by remember { mutableStateOf(false) }
상태 호이스팅해주세요!

2024-03-31 16:32 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/completesignup/CompleteSignupScreen.kt
> +fun CompleteSignupScreen(modifier: Modifier = Modifier, onBackClicked: () -> Unit = {}) {
```suggestion
fun CompleteSignupScreen(
     modifier: Modifier = Modifier, 
     onBackClicked: () -> Unit = {}
) {
```

2024-03-31 16:32 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/completesignup/CompleteSignupScreen.kt
> +fun CompleteSignupScreen(modifier: Modifier = Modifier, onBackClicked: () -> Unit = {}) {
[Compose Convention](https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-component-api-guidelines.md) 을 참고해보세요!

2024-03-31 16:32 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/ui/theme/Color.kt
> +val ColorError = Color(0xFFF05D3D)
Android 트랙에서 테마를 정의할 필요가 보이네요 수요일에 정해봅시다

2024-03-31 16:33 UTC, yunjaena reviewed
그리고 폴더명 명도 feature_signup 이 아니라 feature 안에 signup에 들어가야될것 같고 별도의 모듈로 분리하면 좋을것 같네요.

2024-04-02 07:12 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/accountauth/AccountAuthScreen.kt
> +
제거했습니다!

2024-04-02 07:23 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +    var isButtonClicked by remember { mutableStateOf(false) }
수정해놓겠습니다!

2024-04-02 07:36 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/BusinessAuthScreen.kt
> +                fontWeight = Bold,
커스텀 테마 만들어보면서 공부해보겠습니다!

2024-04-02 07:36 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/BusinessAuthScreen.kt
> +    val itemList: MutableList<String> = mutableListOf()
알겠습니다!

2024-04-02 07:36 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/completesignup/CompleteSignupScreen.kt
> +fun CompleteSignupScreen(modifier: Modifier = Modifier, onBackClicked: () -> Unit = {}) {
감사합니다! 참고하겠습니다!

2024-04-02 07:45 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/accountauth/AccountAuthScreen.kt
> +                    color = Color(0xFFF7941E),
수정한줄알았는데 누락되었나보네요..! 다시 확인해보겠습니다!

2024-04-11 13:28 UTC, yunjaena requested changes
수고했습니다 comment 확인해주세요 :) 
feature_signup 보다는 :feature:signup으로 변경하는게 좋아보입니다.

2024-04-11 13:28 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +                                withStyle(style = SpanStyle(color = Color(0xFFF7941E))) {
Color resource 사용해주세요 :)

2024-04-11 13:28 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +fun StoreList(item: MutableList<String>, onSelected: () -> Unit = {}) {
MutabeList를 사용한 이유가 뭔가요?

2024-04-11 13:28 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +    var showBottomSheet by remember { mutableStateOf(false) }
상태 호이스팅으로 viewModel에서 state를 관리할 수 있지 않을까요?

2024-04-11 13:28 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/accountsetup/AccountSetupScreen.kt
> +                    start = Offset(0f - 40, 0f),
0f - 40f면 -40f 아닌가요?

2024-04-11 13:28 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/accountsetup/AccountSetupScreen.kt
> +                enabled = state.id.isNotEmpty() && state.password.isNotEmpty() && state.passwordConfirm.isNotEmpty() && state.email.isNotEmpty(),
state로 관리 하기 힘들면 확장 함수를 만들면 어떨까요?

val xxxState.isPasswordEnabled: Boolean get() = id.isNotEmpty() && password.isNotEmpty() && passwordConfirm.isNotEmpty() && email.isNotEmpty()

아니면 도메인에서 로직으로 처리해도 좋을것 같습니다.

2024-04-11 13:28 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/BusinessAuthScreen.kt
> +    var phoneNumber by remember { mutableStateOf("") }
상태 호이스팅해주세요 :)

2024-04-11 13:28 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/BusinessAuthScreen.kt
> +        modifier = Modifier
이 부분은 외부에서 modifier를 받는게 좋아보입니다.

2024-04-11 13:28 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +                        .padding(top = 8.dp, bottom = 8.dp)
padding(vertical = 8.dp)로 변경해주세요

2024-04-11 13:28 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +                            .width(195.dp)
버튼 width가 가득차게 되어있는 디자인인가요? 아닌 경우는 fillMaxWidth()에서 패딩을 주는게 좋아보입니다. (작은 디바이스 + 큰 디바이스 대응)

2024-04-11 15:03 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +fun StoreList(item: MutableList<String>, onSelected: () -> Unit = {}) {
ui 확인하려고 테스트 용으로 넣었습니다!

2024-04-11 15:09 UTC, ThirFir commented on business/src/main/java/in/koreatech/business/feature_signup/textfield/LinedTextField.kt
> +    var focused by remember { mutableStateOf(false) }
사용하지 않는 변수인 것 같아요. 혹시 선언하신 이유가 뭔가요?

2024-04-11 16:23 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +fun StoreList(item: MutableList<String>, onSelected: () -> Unit = {}) {
ImmutableList를 쓰는것을 추천드려요 아니면 @Immutable로 맵핑한 List를 쓰는게 좋아보이네요 :) 

참고
- https://medium.com/androiddevelopers/jetpack-compose-strong-skipping-mode-explained-cbdb2aa4b900
- https://medium.com/androiddevelopers/jetpack-compose-stability-explained-79c10db270c8

2024-04-14 07:47 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/accountsetup/AccountSetupScreen.kt
> +                    start = Offset(0f - 40, 0f),
수정했습니다!

2024-04-14 07:50 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/BusinessAuthScreen.kt
> +        modifier = Modifier
수정했습니다!

2024-04-14 08:41 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/textfield/LinedTextField.kt
> +    var focused by remember { mutableStateOf(false) }
테스트할 때 사용한 변수 같은데 안 지웠네요. 지우겠습니다.

2024-04-14 08:41 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/BusinessAuthScreen.kt
> +                fontWeight = Bold,
알겠습니당

2024-04-14 08:44 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +                                withStyle(style = SpanStyle(color = Color(0xFFF7941E))) {
수정했습니다!

2024-04-14 09:05 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +                        .padding(top = 8.dp, bottom = 8.dp)
수정했습니다!

2024-04-14 09:11 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +    var showBottomSheet by remember { mutableStateOf(false) }
뷰모델 추가하면 수정하도록 하겠습니다!

2024-04-14 11:06 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/BusinessAuthScreen.kt
> +    var phoneNumber by remember { mutableStateOf("") }
뷰모델 만들 때 바로 반영하겠습니다!

2024-04-14 11:32 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +                            .width(195.dp)
수정했습니다!

2024-04-14 12:21 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/businessauth/SearchStoreScreen.kt
> +fun StoreList(item: MutableList<String>, onSelected: () -> Unit = {}) {
참고하겠습니다. 감사합니다!

2024-04-14 15:09 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature_signup/accountsetup/AccountSetupScreen.kt
> +                enabled = state.id.isNotEmpty() && state.password.isNotEmpty() && state.passwordConfirm.isNotEmpty() && state.email.isNotEmpty(),
확장 함수 만들었습니다!

2024-04-14 15:11 UTC, ThirFir approved these changes
고생하셨습니다. 👍🤩🐱🐴

2024-04-14 15:37 UTC, hsgo2430 approved these changes
정말 고생하셨습니다!!

2024-04-14 15:37 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupScreen.kt
> +    viewModel: AccountSetupViewModel = hiltViewModel(),
뷰모델이 있으면 Preview를 할 수 없어요!
뷰모델은 AccountSetupScreenLmpl라는 함수에 선언하고 Preview를 위한  AccountSetupScreen 함수를 만들어 보시는 것도 좋을것 같네요!

2024-04-15 05:28 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupScreen.kt
> +    viewModel: AccountSetupViewModel = hiltViewModel(),
아하.. 그동안 불편하게 작업했었는데..감사합니다!

2024-04-15 12:45 UTC, yunjaena approved these changes

2024-04-15 13:15 UTC, merged