사장님 비밀번호 변경 기능 구현
BCSDLab/KOIN_ANDROID pull request #216
Opened 2024-04-08 06:50 UTC by hsgo2430

사장님 비밀번호 찾기 기능을 구현하였습니다.

2024-04-08 16:31 UTC, yunjaena reviewed
수고했습니다! comment 확인해주세요 :)

2024-04-08 16:31 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
>                  .width(40.dp)
size로 변경해주세요 :)

2024-04-08 16:31 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +            colors = if(state.password.isBlank() || state.passwordChecked.isBlank()) ButtonDefaults.buttonColors(Gray5)
passwordIsValid state를 가지고 있는게 어떨까요? 테스트할때도 용의해보입니다.

2024-04-08 16:31 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +            onClick = { viewModel.changePassword(state.email, state.password, state.passwordChecked) },
중복 클릭에 대한 대책이 있으면 좋을것 같습니다 :) ViewModel에서 처리하거나 Debounce 개념에 대해서 알아보면 좋을것 같네요!

2024-04-08 16:31 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +            is ChangePasswordSideEffect.NotCoincidePassword -> showMessage("비밀번호가 일치하지 않습니다.")
stringResrouce를 사용해주세요.

2024-04-08 16:31 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/util/ToastMessage.kt
> +fun showMessage(message: String){
Core 모듈에 정의해도 좋아보입니다.

2024-04-08 16:31 UTC, yunjaena commented on data/src/main/java/in/koreatech/koin/data/repository/OwnerChangePasswordRepositoryImpl.kt
> +        return try {
CancellationException에대해서 공부해보면 좋을것 같습니다 :)

2024-04-08 16:31 UTC, yunjaena commented on domain/src/main/java/in/koreatech/koin/domain/usecase/owner/OwnerAuthenticateCode.kt
> +        return when (authCode) {
email도 빈값을 검사해줘야 되지 않을까요?

2024-04-08 16:31 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +                        modifier = modifier.fillMaxWidth(),
```suggestion
                        modifier = Modifier.fillMaxWidth(),
```
Modifier.fillMaxWidth()
로 변경해야됩니다.

2024-04-08 16:31 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +                        if (state.passwordChecked.isEmpty()) {
해당 state도 viewModel에 변경해서 테스트 코드를 추가해보면 어떨까요?

2024-04-08 16:31 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordViewModel.kt
> +    fun insertPassword(password: String) = intent{
보통 public fun이 private보다 위에 있습니다 :) 
public
public
private => public에 연관된 메서드
...
public
private => public에 연관된 메서드

2024-04-08 16:31 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/passwordauthentication/PasswordAuthenticationScreen.kt
> +                viewModel.authenticateCode(state.email, state.authenticationCode)
email 입력 받을때 trim 처리를 해주는거는 어떨까요?

2024-04-08 16:31 UTC, yunjaena commented
conflict 확인해주세요!

2024-04-09 08:19 UTC, Jokwanhee reviewed
고생했습니다~ 👍

2024-04-09 08:19 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordSideEffect.kt
> +    object ToastNullEmail: ChangePasswordSideEffect()
object 대신 kotlin 1.9.0 부터 추가된 data object 를 사용해봤는데, 로깅을 찍어볼 때 훨씬 직관적으로 어떤 object 인 지 확인할 수 있어서 좋았습니다~ [참고!]

2024-04-09 08:19 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordViewModel.kt
> +    savedStateHandle: SavedStateHandle
👍

2024-04-09 08:19 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature_changepassword/navigator/FeatureChangePassword.kt
> +private fun navigateToRandomScreen(
navigation route 정의 클래스를 아래 코드를 참고해보시면 깔끔하게 정리하실 수 있을 것 같습니다!

(아래는 sunflower 코드인데, 참고하면 훨씬 깔끔한 코드를 작성하실 수 있을 것 같습니다!!)
https://github.com/android/sunflower/blob/main/app/src/main/java/com/google/samples/apps/sunflower/compose/Screen.kt

2024-04-09 08:19 UTC, Jokwanhee commented on business/src/main/res/values/strings.xml
> +    <string name="back_arrow">backArrow</string>
개인적으로 string resource name 을 정의할 때, 규칙이 있었으면 좋을 것 같습니다! 나중에 찾기도 힘들고 지저분해집니다 ㅠ
예시로 기존 koin 에서 사용된 string resource 파일을 보면 회원가입(sign_up)에 대한 네이밍을 통일한 것을 알 수 있습니다!
```kotlin
<string name="signup_email_sending">이메일 전송 중</string>
<string name="signup_term_check_message_ask">&quot;동의&quot; 체크 박스에 체크를 한 후 이메일 인증하기 버튼을 클릭하면 본 약관에 동의하는 것으로 간주합니다.</string>
<string name="signup_error_email_already_send_or_email_requested">이미 가입한 계정이거나\n이메일 전송을 요청하였습니다.</string>
...
```

2024-04-09 08:19 UTC, Jokwanhee commented on domain/src/main/java/in/koreatech/koin/domain/util/ext/ValidationExtensions.kt
> +    val emailRegex = "^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"
EmailUtil.kt 클래스로 옮겨주시면 좋을 것 같습니다~

2024-04-09 12:20 UTC, Yang-Seungmin commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +    val state = viewModel.collectAsState().value
`collectAsStateWithLifeCycle()`을 이용하여 라이프사이클을 인지하여 상태를 collect할 수 있습니다

2024-04-10 03:21 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +    val state = viewModel.collectAsState().value
@Yang-Seungmin 
제가 알기로는 orbit 사용해서 라이프사이클을 저 oribit collectAsState api 가 처리해주는 것으로 알고있습니다! 👍

2024-04-13 05:44 UTC, hsgo2430 commented on business/src/main/res/values/strings.xml
> +    <string name="back_arrow">backArrow</string>
이런식으로 관련된 내용이 먼저 오도록 바꿨습니다!
<!--패스워드 관련-->
    <string name="password_condition">* 특수문자 포함 영어와 숫자 조합 6~18 자리</string>
    <string name="password_not_coincide">비밀번호가 일치하지 않습니다.</string>
    <string name="password_please_sign_in_with_new_password">비밀번호가 변경되었습니다.\n새로운 비밀번호로 로그인 부탁드립니다.</string>
    <string name="password_change_complete">비밀번호 변경 완료</string>
    <string name="password_confirm">비밀번호 확인</string>
    <string name="password_new">새 비밀번호</string>
    <string name="password_changing">비밀번호 변경하기</string>
    <string name="password_find">비밀번호 찾기</string>
    <string name="password_change">비밀번호 변경</string>

2024-04-14 15:42 UTC, hsgo2430 commented on domain/src/main/java/in/koreatech/koin/domain/usecase/owner/OwnerAuthenticateCode.kt
> +        return when (authCode) {
추가하였습니다!

2024-04-14 15:43 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/util/ToastMessage.kt
> +fun showMessage(message: String){
제거하고 Core모듈에 있는 함수를 사용했습니다!

2024-04-14 15:43 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +            onClick = { viewModel.changePassword(state.email, state.password, state.passwordChecked) },
공부하고 구현해보겠습니다!

2024-04-14 15:43 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +                        if (state.passwordChecked.isEmpty()) {
state의 확장함수를 만들었습니다!

2024-04-14 15:43 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature_changepassword/passwordauthentication/PasswordAuthenticationScreen.kt
> +                viewModel.authenticateCode(state.email, state.authenticationCode)
trim 추가하겠습니다!

2024-04-14 15:44 UTC, hsgo2430 commented on data/src/main/java/in/koreatech/koin/data/repository/OwnerChangePasswordRepositoryImpl.kt
> +        return try {
CancellationException 공부해보고 적용해보겠습니다

2024-05-07 10:35 UTC, yunjaena requested changes
수고했습니다. comment 확인해주세요 :)
그리고 스크린샷에서 오류 문구랑 아이콘이랑 정렬이 안맞는거 같은데 확인해보시면 좋을것 같습니다.

2024-05-07 10:35 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +                viewModel.coincidePasswordReset()
두개 메소드를 viewModel 내부에서 호출하는게 좋아보입니다.

2024-05-07 10:35 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +                newCheckedPassword -> viewModel.insertPasswordChecked(newCheckedPassword)
해당 메소드도 마찬가지로 내부에서 호출되는게 좋아보입니다.

2024-05-07 10:35 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordViewModel.kt
> +                .debounce(500L)
비밀번호를 실시간으로 체크하는게 아니면 debounce가 필요 없어보입니다.

2024-05-07 10:35 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/passwordauthentication/PasswordAuthenticationScreen.kt
> +fun HandleSideEffects(viewModel: PasswordAuthenticationViewModel, email: String, navigateToChangePassword: (email: String) -> Unit) {
해당 메서드는 private하면 좋을것 같습니다.

2024-05-07 10:35 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature_changepassword/passwordauthentication/PasswordAuthenticationSideEffect.kt
> +    object ToastIsNotEmail: PasswordAuthenticationSideEffect()
data class ShowMessage(type: ErrorType): PasswordAuthenticationSideEffect()

으로 지정하는게 확장성도 있지 않고 ToastMessage가 아닌 SnackBar라던지 다른타입의 뷰로 변경할때 용이해 보입니다.

2024-05-07 10:35 UTC, yunjaena commented on data/src/main/java/in/koreatech/koin/data/repository/OwnerChangePasswordRepositoryImpl.kt
> +        return try {
@hsgo2430 반영되었나요?

2024-05-07 10:46 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature_changepassword/passwordauthentication/PasswordAuthenticationScreen.kt
> +fun HandleSideEffects(viewModel: PasswordAuthenticationViewModel, email: String, navigateToChangePassword: (email: String) -> Unit) {
private로 변경하였습니다!

2024-05-07 10:49 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordViewModel.kt
> +                .debounce(500L)
넵 알겠습니다

2024-05-07 10:51 UTC, hsgo2430 commented
> 수고했습니다. comment 확인해주세요 :) 그리고 스크린샷에서 오류 문구랑 아이콘이랑 정렬이 안맞는거 같은데 확인해보시면 좋을것 같습니다.

지금은 수정이 완료된 상황입니다!

2024-05-07 11:02 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +                viewModel.coincidePasswordReset()
내부에서 호출하도록 변경하였습니다!

2024-05-07 11:03 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature_changepassword/changepassword/ChangePasswordScreen.kt
> +                newCheckedPassword -> viewModel.insertPasswordChecked(newCheckedPassword)
viewModel.fillAllPasswords() 도 내부에서 호출하도록 변경하였습니다

2024-05-07 11:32 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature_changepassword/passwordauthentication/PasswordAuthenticationSideEffect.kt
> +    object ToastIsNotEmail: PasswordAuthenticationSideEffect()
말씀하신대로 한번 적용해 보았습니다!

2024-05-07 13:37 UTC, yunjaena approved these changes
LGTM 수고했습니다

2024-05-08 04:44 UTC, Jokwanhee approved these changes
고생했습니다~

2024-05-08 04:49 UTC, merged