[Fix] 유저 정보 수정, 시간표 QA
BCSDLab/KOIN_ANDROID pull request #244
Opened 2024-04-26 10:54 UTC by nodobi

### 개요
유저 정보 수정, 시간표 QA 반영

### 상세 작업 내용
- close #240
  - 정보 수정 화면에서 이름을 변경할 수 없던 현상
  
- close #241
  - xml 파일에 텍스트가 tools:text 로 등록되어 있던 문제
    
- close #242 
  - 기존에 사용하는 닉네임을 그대로 중복 체크 하는 경우에도 중복된 닉네임이라 인식하여 수정이 안되던 현상
  - 뷰모델에서 상태를 결정하여 토스트 메세지를 띄우도록 수정

- close #243 
  - 다이얼로그 클릭 이벤트가 올바르게 설정되어 있지 않아 발생

- 기타
    - LiveData 라이브러리가 2.7.0 으로 업데이트됨에 따라 `SingleLiveEvent.call()` 수정

2024-04-26 10:59 UTC, nodobi commented on core/src/main/java/in/koreatech/koin/core/viewmodel/SingleLiveEvent.kt
>      }
라이브러리 버전이 2.5.1 -> 2.7.0 으로 변경 되면서 null 값을 사용할 수 없게 되어 Unit 인 경우 사용하도록 변경했습니다

[(관련링크)](https://github.com/androidx/androidx/commit/fee12f73703eb830671afca539014dfcd7e4f128)

2024-04-26 12:39 UTC, ThirFir approved these changes
고생하셨습니다🔥

2024-04-29 15:45 UTC, Jokwanhee approved these changes
고생하셨습니다~~ SingleLiveEvent 에서 저번에 NPE 뜬 적 있었는데 그 이유였군요!! 좋은 정보 얻어갑니다~

2024-04-29 15:45 UTC, Jokwanhee commented on koin/src/main/java/in/koreatech/koin/ui/userinfo/UserInfoEditActivity.kt
> +                    }
임시 방편으로는 메시지를 when으로 해도 좋을 것 같지만, when 구절을 밖으로 빼는 것이 좋아보이네요! 
- 닉네임이 이전 닉네임과 동일할 때, TextField 색상을 주황색으로 변경한다면?
- 닉네임이 이미 존재할 때, TextField를 빨간색으로 나타내고 스낵바가 뜬다면?
- 닉네임이 가능할 때, 가능하다는 ToastMessage를 띄운다면?

뭐 요런 고민을 했을 때, 굳이 toast message 안에 넣지 않아도 괜찮을 것 같다는 **개인적인 의견**입니다 ^_^..

2024-04-30 00:45 UTC, nayunjae requested changes
수고하셨습니다. 커멘트를 확인해주세요.

2024-04-30 00:45 UTC, nayunjae commented on koin/src/main/java/in/koreatech/koin/ui/timetable/TimetableSelectMajorDialog.java
> +                    majorDialogListener.sendActivity("electronic", 1);
상수나 enum으로 정의해주세요.

2024-04-30 00:45 UTC, nayunjae commented on koin/src/main/java/in/koreatech/koin/ui/timetable/TimetableSelectMajorDialog.java
> +                    majorDialogListener.sendActivity("mechanical", 5);
상수나 enum으로 정의해주세요.

2024-04-30 00:45 UTC, nayunjae commented on koin/src/main/java/in/koreatech/koin/ui/userinfo/viewmodel/UserInfoEditViewModel.kt
> +        if (nickname == (user.value as User.Student).nickname) {
as? 를 사용하는게 좋아보입니다.

2024-05-01 14:53 UTC, nodobi commented on koin/src/main/java/in/koreatech/koin/ui/userinfo/viewmodel/UserInfoEditViewModel.kt
> +        if (nickname == (user.value as User.Student).nickname) {
수정했습니다. 감사합니다! 😁

2024-05-01 14:54 UTC, nodobi commented on koin/src/main/java/in/koreatech/koin/ui/userinfo/UserInfoEditActivity.kt
> +                    }
이후 로직이 추가될 여지가 있다는 점을 생각해보면 말씀해주신 방법대로 하는게 좋아보여요! 
수정했습니다! 😁

2024-05-01 14:54 UTC, nodobi commented on koin/src/main/java/in/koreatech/koin/ui/timetable/TimetableSelectMajorDialog.java
> +                    majorDialogListener.sendActivity("electronic", 1);
관희님이 시간표에 해당하는 부분을 리팩토링 하고 있어서 추가적인 리소스를 사용하지 않는게 좋다고 판단했습니다..!
현재 오류가 발생하지 않도록 단순 오탈자만 수정 했는데 추가적인 작업을 하는게 좋을까요..?

2024-05-01 14:57 UTC, yunjaena commented on koin/src/main/java/in/koreatech/koin/ui/timetable/TimetableSelectMajorDialog.java
> +                    majorDialogListener.sendActivity("electronic", 1);
그러면 넘겨도 될것 같네요.

2024-05-02 00:31 UTC, merged