feature/business_login
BCSDLab/KOIN_ANDROID pull request #269
Opened 2024-05-13 03:44 UTC by hsgo2430

### **개요**

>-----------------

- 사장님 로그인 기능 

### **상세 작업 내용**
>-----
- 사장님 로그인 기능 추가
- 아이디 및 비밀번호가 공란, 가입되지 않은 아이디, 틀린 비밀번호  입력시 토스트 메시지로 해당 상황을 알려주도록 구현

### **작업 결과물**

<img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/b332f138-2893-4a2b-a7a3-e53789453018 width="250" height="500">

로그인 화면

<img src= https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/6d03de21-c11e-4d9c-bb96-2b429c1416d2 width="250" height="500">

빈칸 메시지

<img src=  https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/9af8bfbc-ead5-445f-ba49-7985b234cb28 width="250" height="500">

없는 아이디 메시지

<img src=  https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/c8c4f853-0812-45dd-8c10-4a47a0c8b53f width="250" height="500">

틀린 비밀번호 메시지

2024-05-14 11:55 UTC, yunjaena requested changes
수고했습니다 :) 커멘트 확인해주세요 ~

2024-05-14 11:55 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/BusinessMainActivity.kt
> +                    SignInNavigator()
사용안하는 코드는 지우면 좋을것 같습니다. 또한 Scaffold를 사용해보는거는 어떨까요?

2024-05-14 11:55 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/changepassword/changepassword/ChangePasswordViewModel.kt
>              state.copy(notCoincidePW = false)
notCoincidePW  isValidate는 어떨까요?

2024-05-14 11:55 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            if(state.isFilledIdEmailField) viewModel.login(state.id.trim(), state.password.trim())
해당 로직은 viewModel에서 체크하는거는 어떨까요?

2024-05-14 11:55 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +                    Divider(
다크모드일때 확인해봤나요?

2024-05-14 11:55 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            modifier = modifier
modifier => Modifier

2024-05-14 11:55 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            modifier = modifier
modifier => Modifier

2024-05-14 11:55 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            modifier = modifier
modifier => Modifier

2024-05-14 11:55 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            modifier = modifier
modifier => Modifier

2024-05-14 11:55 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +                modifier = modifier.fillMaxWidth()
modifier => Modifie

2024-05-14 11:55 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            modifier = modifier
modifier => Modifie

2024-05-14 11:55 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +fun PreViewSignInScreen(){
Default 매개변수를 넣어놓으면 어떨까요?

2024-05-14 11:55 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInViewModel.kt
> +    private fun fillAllPasswords() = intent {
validatePassword()가 좋아보입니다.  fillAllPasswords는 비밀번호를 전체 채워넣는 느낌이네요.

2024-05-15 06:22 UTC, yunjaena requested changes
Comment  확인해주세요 :)

2024-05-15 06:22 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +           viewModel.login(state.id.trim(), state.password.trim())
state에 가지고 있는 정보면 viewModel.login()으로도 가능할것 같네요.

2024-05-15 06:22 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +    modifier: Modifier = Modifier,
Preview에 default 매개변수를 넣는게 아니라 Screen쪽에 말한거였어요!

2024-05-15 06:22 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInViewModel.kt
> +        if(SignInState().validateField){
객체를 새로 생성한 이유가 있나요?

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInViewModel.kt
> +    private fun fillAllPasswords() = intent {
넵 수정하겠습니다!

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            modifier = modifier
수정하겠습니다!

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +                modifier = modifier.fillMaxWidth()
수정하겠습니다!

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            modifier = modifier
수정하겠습니다!

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            modifier = modifier
수정하겠습니다!

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            modifier = modifier
수정하겠습니다!

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            modifier = modifier
수정하겠습니다!

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            if(state.isFilledIdEmailField) viewModel.login(state.id.trim(), state.password.trim())
뷰모델에서 체크하는 걸로 변경하였습니다!

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +fun PreViewSignInScreen(){
Impl 함수처럼 매개변수 넣어서 한번 해보겠습니다

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +                    Divider(
@Preview(
    showBackground = true,
    uiMode = UI_MODE_NIGHT_YES,
    name = "DefaultPreviewDark"
)
를 통해 다크모드 확인해봤는데 괜찮았습니다!

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/changepassword/changepassword/ChangePasswordViewModel.kt
>              state.copy(notCoincidePW = false)
말씀하신 단어가 더 적합한거같아서 바꿨습니다!

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/BusinessMainActivity.kt
> +                    SignInNavigator()
사용안하는 코드 지우고 Scaffold로 TopAppBar를 만들어봤습니다.

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +           viewModel.login(state.id.trim(), state.password.trim())
그렇겠네요! viewModel이 상태를 가지고 있으니까 안에서 넣도록 하겠습니다!

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +    modifier: Modifier = Modifier,
앗.... 어쩐지 뭔가 이상했어요... Screen으로 수정헀습니다!

2024-05-18 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInViewModel.kt
> +        if(SignInState().validateField){
헉... viewModel이 가지고 있는 state의 접근 방법이 저건줄 알았는데 다시 생각해보니까 새로 생성하고 그 객체의 vaildateField에 접근하는거네요....
수정하겠습니다!

2024-05-19 12:50 UTC, yunjaena requested changes
변수명 확인해주세요.

2024-05-19 12:50 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/changepassword/changepassword/ChangePasswordState.kt
> +    val PasswordsFieldIsValidate: Boolean = false
```suggestion
    val passwordsFieldIsValid: Boolean = false
```

2024-09-13 09:30 UTC, closed without merging