[Feature/business_signup] 사장님 회원가입 페이지 구현
BCSDLab/KOIN_ANDROID pull request #277
Opened 2024-05-18 12:36 UTC by skdud0629

### **개요**

- 사장님 회원가입 구현
   - 약관 동의 / 기본정보 입력/사업자 인증/ 가게 검색 페이지

### **작업 상세내용**
기존 ui 수정 및 메일 인증을 메세지 인증으로 변경
---
- **약관 동의**
   - <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/f8943870-1bf9-4337-a451-bc8a39f730ad width="150" height="300">

> 

- **기본정보 입력**
   - 비밀번호, 휴대폰 번호 분기 처리 및 메세지 인증 구현
   - 조건에 맞지 않을 때 경고 메세지를 띄우고 버튼 비활성화
   - 기존에 사용된 메일 인증을 sms api를 사용하면서 문자 인증으로 변경함
   - <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/6dc618c8-59e2-4171-b778-e07866b5e961 width="150" height="300">

> 

- **사업자 인증**
   - 가게 검색 및 이미지 업로드
   - photo picker & presigned url 사용 
   - <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/ca0d6b17-9b40-4283-af8d-f277cc914c3e width="150" height="300">  <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/1338bf68-0260-472c-abb4-8eec07798dfe width="150" height="300">

2024-05-18 14:39 UTC, yunjaena requested changes
수고했습니다! comment 확인해주세요! 그리고 pr은 나눠서 올려야지 리뷰하기 좋습니다 😄

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/di/resource/TokenLocalDataSource.kt
> +class TokenLocalDataSource @Inject constructor(
학생용이랑 사장님용이 다른 용도이면 다른 클래스로 만들어서 주입하는게 좋지 않을까요?

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupScreen.kt
> +                        /* 아이디 중복 확인 */
TO-DO를 사용하시면 좋을것 같습니다 :) 추후에 누락한 기능있는지 확인할 수 있어요!

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupScreen.kt
> +                isError = !state.password.isValidPassword() && state.password.isNotEmpty(),
isError state를 viewModel에서 처리하면 좋지 않을까요?

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupScreen.kt
> +                enabled = state.signUpContinuationError == null && state.isButtonEnabled,
isButtonEnabled에서 error 체크를 하는것보다 해당 state에 해당 검사 로직 처리가 필요해보이네요.

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupState.kt
> +    val isButtonEnabled: Boolean
전에 모델에서 get()로 하는 방법으로 소개했었는데요. 더 좋은 방법을 찾았습니다.

```kotlin
data class AccountSetupState(
    val id: String = "",
    val password: String = "",
    val passwordConfirm: String = "",
    val phoneNumber: String = "",
    val authCode: String = "",
    val signupContinuationState: SignupContinuationState = SignupContinuationState.RequestedEmailValidation,
    val signUpContinuationError:Throwable? = null,
    val isLoading: Boolean = false,
    val isButtonEnabled: Boolean = false
)
```

이렇게 값을 가지고 viewModel에서 id 또는 password를 snapshowFlow로 옵져빙해서 값을 업데이트 처리를 하면 될것 같아요

https://www.youtube.com/watch?v=b2z1jvD4VMQ

15분 49초 참고해주세요.

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupViewModel.kt
> +                    reduce { state.copy(signupContinuationState = it) }
한번에 처리할 수 있지 않나요?

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthState.kt
> +    val isButtonEnabled: Boolean
아까 영상 링크랑 동일하게 처리해보는거는 어떨까요?

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthViewModel.kt
> +                    reduce {
reduce를 여러번 사용하지 않고 한번에 처리가능할것 같습니다.

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/businessauth/SearchStoreState.kt
> +    val search:String="",
띄어쓰기
```suggestion
    val search: String= "",
```

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/businessauth/SearchStoreViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
viewModelScope에서 웬만해서 Dispatcher.IO를 사용하지 마세요. 안에서 withContext또는 launch에서 디스패쳐를 바꾸시는게 좋아보입니다. 그리고 여기서는 사용할 필요가 없어보이네요.

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/checkterm/CheckTermScreen.kt
> +                            viewModel.onAllTermCheckedChanged(!state.isAllTermChecked)
state값을 viewModel이 알고 있는게 값을 보낼필요가 있을까요?

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/checkterm/CheckTermScreen.kt
> +                            viewModel.onPrivacyTermCheckedChanged(!state.isCheckedPrivacyTerms)
state값을 viewModel이 알고 있는게 값을 보낼필요가 있을까요?

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/checkterm/CheckTermScreen.kt
> +                            viewModel.onAllTermCheckedChanged(state.isCheckedPrivacyTerms && state.isCheckedKoinTerms)
state값을 viewModel이 알고 있으므로 해당 로직을 여기서 처리할 필요가 없어보입니다.

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/textfield/SearchTextField.kt
> +                    .background(color=Gray5, shape = RoundedCornerShape(4.dp))
```suggestion
                    .background(color = Gray5, shape = RoundedCornerShape(4.dp))
```

2024-05-18 14:39 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/ui/theme/Theme.kt
> +   //     typography = Typography,
사용안하면 지워주세요.

2024-05-18 14:39 UTC, yunjaena commented on data/src/main/java/in/koreatech/koin/data/repository/OwnerSignupRepositoryImpl.kt
> +        } catch (e: HttpException) {
CancellationException에대해서 공부해보고 적용해보세요.

2024-05-18 14:39 UTC, yunjaena commented on data/src/main/java/in/koreatech/koin/data/repository/OwnerVerificationCodeRepositoryImpl.kt
> +        } catch (e: HttpException) {
CancellactionException 확인해주세요!

2024-05-18 14:39 UTC, yunjaena commented on data/src/main/java/in/koreatech/koin/data/repository/PreSignedUrlRepositoryImpl.kt
> +            Result.failure(e)
동일하게 try catch를 사용하면 mapper를 만들어보는게 어떨까요?

2024-05-18 14:39 UTC, yunjaena commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/BusinessSignupCheckUseCase.kt
> +                    Result.failure(authToken.exceptionOrNull()!!)
!!는 가급하면 사용하지 않는게 좋습니다.

2024-05-18 19:13 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/ui/theme/Theme.kt
> +   //     typography = Typography,
반영했습니당

2024-05-19 10:12 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupViewModel.kt
> +                    reduce { state.copy(signupContinuationState = it) }
수정했습니당

2024-05-19 10:12 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthViewModel.kt
> +                    reduce {
수정했습니당

2024-05-19 10:14 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/signup/checkterm/CheckTermScreen.kt
> +                            viewModel.onAllTermCheckedChanged(!state.isAllTermChecked)
아하 그러네용 수정하겠습니다!

2024-05-19 10:24 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/signup/businessauth/SearchStoreViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
아하 코루틴 지식이 부족한 탓에 너무 막 써버렸네요..! 참고하겠습니다!

2024-06-05 02:09 UTC, skdud0629 commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/BusinessSignupCheckUseCase.kt
> +                    Result.failure(authToken.exceptionOrNull()!!)
변경했습니당

2024-06-05 12:47 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupScreen.kt
> +                isError = !state.password.isValidPassword() && state.password.isNotEmpty(),
반영했습니다!

2024-06-05 15:47 UTC, yunjaena requested changes
나영님 comment 참고해주세요!

2024-06-05 15:47 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupState.kt
> +    val isButtonEnabled: Boolean
ViewModel에 적용해봤어요 한번 테스트 해보실래요?
// AccountSetupViewModel.kt

```kotlin
   private val passwordFlow = snapshotFlow {
        container.stateFlow.value.password
    }
    private val idFlow = snapshotFlow {
        container.stateFlow.value.id
    }
    private val passwordConfirmFlow = snapshotFlow {
        container.stateFlow.value.passwordConfirm
    }

    private val phoneNumberFlow = snapshotFlow {
        container.stateFlow.value.phoneNumber
    }

    private val authCodeFlow = snapshotFlow {
        container.stateFlow.value.authCode
    }
    
    init {
        combine(
            passwordFlow,
            idFlow,
            passwordConfirmFlow,
            phoneNumberFlow,
            authCodeFlow
        ) { password, id, passwordConfirm, phoneNumber, authCode ->
            password.isNotEmpty() && id.isNotEmpty() && passwordConfirm.isNotEmpty() && phoneNumber.isNotEmpty() && authCode.isNotEmpty()
        }.onEach {
            updateButton(it)
        }.launchIn(viewModelScope)
    }

    private fun updateButton(enabled: Boolean) = intent {
        reduce {
            state.copy(isButtonEnabled = enabled)
        }
    }
```

2024-06-05 15:47 UTC, yunjaena commented
conflict 해결해주세요 :)

2024-06-05 15:48 UTC, yunjaena requested changes

2024-06-05 15:48 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/di/resource/TokenLocalDataSource.kt
> +class TokenLocalDataSource @Inject constructor(
@skdud0629 이부분도 확인해주세요!

2024-06-08 08:21 UTC, skdud0629 commented on data/src/main/java/in/koreatech/koin/data/repository/PreSignedUrlRepositoryImpl.kt
> +            Result.failure(e)
반영했습니당

2024-06-09 13:30 UTC, yunjaena approved these changes
LGTM 수고하셨습니다.

2024-06-09 14:06 UTC, ThirFir approved these changes
수고하셨습니다.

2024-06-09 14:16 UTC, merged