Feature/hsgo/business the first store insert
BCSDLab/KOIN_ANDROID pull request #278
Opened 2024-05-19 05:52 UTC by hsgo2430

### **개요**

>-----------------

- 사장님 가게등록 일부 구현

### **상세 작업 내용**
>-----
-  카테고리, 가게 이미지, 이름 ,주소 등록 기능 구현

### **작업 결과물**

<img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/92b6e3c3-0637-459a-ad24-2b649c2cace8 width="250" height="500">

가게 정보 기입 화면

<img src=  https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/acba918a-0935-4a48-be82-ebc059a52cc3 width="250" height="500">

카테고리 등록

<img src=  https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/d156688e-6aef-4d2c-aa2d-f9f5f862628f width="250" height="500">

가게 기본 정보 등록

2024-05-19 12:48 UTC, yunjaena requested changes
수고했습니다. comment 확인해주세요.

2024-05-19 12:48 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreen.kt
> +fun InsertDetailInfoScreenImpl(
저번에 comment에도 명시하려다가 놓친부분이 있는데요. Impl가 아니라 여기는 InsertDetailInfoScreen가 되고 밑에 있는 화면이 InsertDetailInfoScreenImpl가 되는게 좋아보이네요.

2024-05-19 12:48 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreen.kt
> +    storeNumber: String = "010-1111-1111"
가게 번호가 잘못 내려올수도 있기 떄문에 빈 값으로 두는게 좋아보입니다.
```suggestion
    storeNumber: String = ""
```

2024-05-19 12:48 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenSideEffect.kt
> +enum class ErrorType {
ErrorType이 광대하게 사용될수 있는 이름이라서 한번 고민해보는게 좋아보입니다.
InsertDetailInfoErrorType 등등.. 아니면 접근제어자로 한정을 짓는것도 방법이 되겠네요.

2024-05-19 12:48 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenViewmodel.kt
> +            val storeBasicInfo = Gson().fromJson(
https://medium.com/@jerry.cho.dev/jetpack-navigation-with-parcelable-f525663b5545
위와 같이 구현해보면 어떨까요?

2024-05-19 12:48 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreen.kt
> +    onBackPressed: () -> Unit = {}
default 이름에다가 실제가게 이름을 넣는거는 안좋아 보입니다. 빈 string으로 놨두는게 좋아보여요

2024-05-19 12:48 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreen.kt
> +                    .height(40.dp)
```suggestion
                    .size(40.dp)
```

2024-05-19 12:48 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreen.kt
> +    textString: String = "가게명",
```suggestion
    textString: String = "",
```

2024-05-19 12:48 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
> +            }
```suggestion
            if(state.isBasicInfoValidate){
                val storeBasicInfo: StoreBasicInfo = StoreBasicInfo(
                    storeName = state.storeName,
                    storeAddress = state.storeAddress,
                    storeImage = state.storeImage.toString(),
                    storeCategory = state.storeCategory
                )
                postSideEffect(InsertBasicInfoScreenSideEffect.NavigateToInsertDetailInfoScreen(storeBasicInfo))
                return@intent
            }

           when {
                state.storeImageIsEmpty -> postSideEffect(InsertBasicInfoScreenSideEffect.ShowMessage(ErrorType.NullStoreImage))
             state.storeName.isEmpty() -> postSideEffect(InsertBasicInfoScreenSideEffect.ShowMessage(ErrorType.NullStoreName))
                  state.storeAddress.isEmpty() -> postSideEffect(InsertBasicInfoScreenSideEffect.ShowMessage(ErrorType.NullStoreAddress))
           }

            }
```

2024-05-20 08:00 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreen.kt
> +fun InsertDetailInfoScreenImpl(
알겠습니다 수정하겠습니다!

2024-05-20 08:03 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreen.kt
> +    storeNumber: String = "010-1111-1111"
넵 알겠습니다!

2024-05-20 08:07 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreen.kt
> +    onBackPressed: () -> Unit = {}
Preview에서 잘 작동하려고 넣어뒀다 삭제를 안했어요...
삭제하도록 할게요!

2024-05-20 08:07 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreen.kt
> +    textString: String = "가게명",
지웠습니다!

2024-05-20 08:09 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
> +            }
확실히 if문보다는 when문이 가독성이 더 좋네요...
if문을 여러번 쓰는 습관은 고치도록 노력해볼게요

2024-05-20 08:11 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenSideEffect.kt
> +enum class ErrorType {
네! 한번 곰곰히 생각해볼게요

2024-05-20 08:12 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenViewmodel.kt
> +            val storeBasicInfo = Gson().fromJson(
넵 알겠습니다!

2024-05-20 13:52 UTC, yunjaena approved these changes
LGTM

2024-06-02 08:41 UTC, skdud0629 approved these changes
수고하셨습니다!

2024-06-02 08:41 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreen.kt
> +                ToastUtil.getInstance().makeShort(message)
토스트로 하신 이유가 있으실까요?

2024-06-02 12:20 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreen.kt
> +                ToastUtil.getInstance().makeShort(message)
사용자도 무슨 오류가 났는지 확인 시켜주기 위해서 토스트 메시지를 사용했습니다!.

2024-06-02 12:21 UTC, merged