가게 상세 정보 등록 페이지 구현
BCSDLab/KOIN_ANDROID pull request #281
Opened 2024-06-05 04:10 UTC by hsgo2430

### **개요**
가게 상세 정보  등록 페이지 구현

---
### **작업 상세내용**

- **가게 상세 정보 등록 페이지**
  - <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/4bf2013a-eae3-4f2e-9715-8df180963dce width="150" height="300">

> 

- **가게 시간 등록 페이지 구현**
   - 휴무 설정 라디오 버튼
   - number picker을 통한 개점 및 폐점 시간 설정
   - <img src= https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/a4ee7ea4-c843-472c-a013-e28c562e4473 width="150" height="300">

> 

- **토스트 메시지 설정**
   - 가게 전화번호, 가게 배달비, 가게 기타 정보 미입력시 토스트 메시지 출력
   - <img src= https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/c9f27956-dc12-4888-b90b-c5e9daa410f2 width="150" height="300">

2024-06-05 13:19 UTC, yunjaena requested changes
@hsgo2430 수고하셨습니다! 디자인과 다른 부분이 많아서 한번 확인 부탁드릴께요!

2024-06-05 13:19 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/OperatingTimeSettingScreen.kt
> +    onSettingStoreTime: (Triple<Hours, Int, Boolean>) -> Unit = {}
Class로 묶는게 좋아보입니다.

2024-06-05 13:19 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/OperatingTimeSettingScreen.kt
> +    operatingTime: OperatingTimeState = OperatingTimeState("00:00", false, "월", "00:00"),
OperatingTimeState가 없으면 empty지 않을까요

2024-06-05 13:19 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenState.kt
> +    val operatingTimeList: List<OperatingTimeState> = listOf(
operating time이 없는게 default가 되어야 되지 않을까요?

2024-06-05 13:19 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenViewmodel.kt
> +            val newList = state.operatingTimeList.toMutableList()
index 체크를 해주세요

2024-06-05 13:19 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenViewmodel.kt
> +            val newList = state.operatingTimeList.toMutableList()
index 체크가 필요합니다.

2024-06-05 13:19 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenViewmodel.kt
> +fun Hours.toTimeString(): String {
여기서 사용하는 함수면 private으로 해주고 공통으로 사용하는 거면 다른 클래스로 빼주세요.

2024-06-05 13:19 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/OperatingTimeSettingScreen.kt
> +    operatingTime: OperatingTimeState = OperatingTimeState("00:00", false, "월", "00:00"),
onShowDialog와 onHideDialog 를 분리해주세요.

2024-06-13 14:30 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenViewmodel.kt
> +fun Hours.toTimeString(): String {
해당 뷰모델에서만 사용하는 것이라서 private로 선언하였습니다!

2024-06-13 14:31 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/OperatingTimeSettingScreen.kt
> +    onSettingStoreTime: (Triple<Hours, Int, Boolean>) -> Unit = {}
data 클래스로 묶어서 사용하였습니다!

2024-06-13 14:33 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/OperatingTimeSettingScreen.kt
> +    operatingTime: OperatingTimeState = OperatingTimeState("00:00", false, "월", "00:00"),
onShowDialog(true to index) 이 코드에서 true가 의미하는 것이 ShowDialog가 True인지 확인하는 것이 아니라 해당 다이얼로그가 개점시간을 등록하는 다이얼로그인지 폐점시간을 등록하는 다이얼로그인지 확인하기 위해 사용된 것입니다.
 하지만 윤재님이 보신것처럼 코드가 해석될 오해의 소지가 있으니 아무래도 수정해야겠네요...

2024-06-13 14:37 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/OperatingTimeSettingScreen.kt
> +    operatingTime: OperatingTimeState = OperatingTimeState("00:00", false, "월", "00:00"),
operatingTime: OperatingTimeState = OperatingTimeState("00:00", false, "월", "00:00")
여기 부분은 OperatingTimeState()로 변경하였습니다

2024-06-13 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenState.kt
> +    val operatingTimeList: List<OperatingTimeState> = listOf(
가게를 등록하는 api인 onwer/shop의 open 스키마에서는 항상 7개의 항목이 들어오도록 설정되어있어서 미리 리스트를 만들어서 넣어놓는것을 default 값으로 설정하였습니다.

2024-06-13 14:48 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenViewmodel.kt
> +            val newList = state.operatingTimeList.toMutableList()
index의 값이 0보다 크거나 같고 리스트의 사이즈보다 작을 때 수행하도록 수정하였습니다.

2024-06-13 14:48 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreenViewmodel.kt
> +            val newList = state.operatingTimeList.toMutableList()
index의 값이 0보다 크거나 같고 리스트의 사이즈보다 작을 때 수행하도록 수정하였습니다.

2024-06-15 10:33 UTC, ThirFir approved these changes
수고하셨습니다!

2024-06-15 10:33 UTC, ThirFir commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreen.kt
> +fun NameTextField(
NameTextField 파일을 만들어서 관리하는 것은 어떤가요?

2024-06-15 10:33 UTC, ThirFir commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreen.kt
> +fun CreateCheckBox(
변수명을 예를 들어 TextCheckBox(그냥 예시입니다)와 같이 명확하게 표현하면 무슨 Composable인지, 그리고 재사용성에서 좋을 거 같습니다!!

2024-06-15 10:33 UTC, ThirFir commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/OperatingTimeSettingScreen.kt
> +fun DayOperatingTImeSetting(
TIme 오타 있네여

2024-06-17 11:09 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreen.kt
> +fun CreateCheckBox(
CreateOptionCheckBox이라는 이름으로 변경하였습니다!

2024-06-17 11:09 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/OperatingTimeSettingScreen.kt
> +fun DayOperatingTImeSetting(
예리한 지적 감사합니다!

2024-06-17 11:10 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertdetailinfo/InsertDetailInfoScreen.kt
> +fun NameTextField(
그러면 좋긴한데 작업 충돌이 날수도 있을거같아서 우선 저 방식을 사용하였습니다!

2024-06-18 01:14 UTC, nayunjae approved these changes
수고했습니다!

2024-06-18 01:15 UTC, yunjaena approved these changes

2024-06-18 01:51 UTC, merged