[Feature] 내 상점 페이지 UI
BCSDLab/KOIN_ANDROID pull request #282
Opened 2024-06-12 01:50 UTC by skdud0629

## **개요**
사장님 내 상점 페이지 UI
- 메뉴 페이지, 이벤트/공지 페이지

## **작업 상세내용**
collapsing tool bar
- **약관 동의**
   - <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/169ea798-cf6b-4eef-8756-497d3fa08abe width="150" height="300">

## **어려웠던 점**
**material2에서는 coordinatelayout을 지원하지 않음**
-  메뉴, 이벤트/공지 페이지의 아이템이 적을 때 화면의 길이가 충분히 길지 않기 때문에 stiky header가 상단에 붙지 않는 문제가 발생함.  
   - 메뉴, 이벤트/공지 페이지 높이를 configuration.screenHeightDp.dp-toolbar height 로 설정해 스크린의 길이가 화면에 꽉 차도록 설정
- 화면을 스크롤 했을 때 toolbar가 collapsing되게 해야 함.
   -  collapsed tool bar를 따로 만들어 화면이 스크롤 된 정도에 따라 visibility 설정

### **이슈사항**
toolbar가 접혔을 때 애니메이션이 부자연스러움

2024-06-12 11:57 UTC, ThirFir commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +    LaunchedEffect(expandedItem) {
이 코드는 무슨 역할인가요?

2024-06-12 11:57 UTC, ThirFir commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +        ScrollView(viewModel)
ViewModel을 직접 전달하는 것보단 필요한 데이터만 전달하는 형태가 좋을 거 같습니다

2024-06-12 11:57 UTC, ThirFir commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +            TopBar(viewModel)
마찬가지로 ViewModel 대신 필요한 데이터만 전달하는 것이 좋을 것 같아요

2024-06-12 11:57 UTC, ThirFir commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +                Row(modifier = Modifier.padding(vertical = 5.dp)) {
같은 Row 형태가 반복되고 있는데, 따로 Composable 함수를 만들어서 for문으로 처리하면 좋을 거 같아요

2024-06-12 11:59 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +            TopBar(viewModel)
넹

2024-06-12 13:45 UTC, yunjaena requested changes
수고하셨습니다! 커멘트 확인해주세요.

2024-06-12 13:45 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +                Row(modifier = Modifier.padding(vertical = 5.dp)) {
lazyColumn에서 items를 사용하면 좋을것 같네요.

2024-06-12 13:45 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +fun ScrollView(viewModel: MyStoreDetailViewModel) {
ScrollView라는 이름은 애매하네요. MyStoreScreen이나 다른 이름으로 가져가면 좋을것 같아요.

2024-06-12 13:45 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +    val list = listOf("Test1", "Test2", "Test3","Test4","Test5","Test6","Test7","Test8","Test9","Test10")
테스트 용으로 넣어놓은 코드인가요?

2024-06-12 13:45 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +    val expandedItem = List(list.size) { rememberSaveable { mutableStateOf(false) } }
ViewModel에서 처리해도 좋을것 같습니다.

2024-06-12 13:45 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +                Text(text = stringResource(R.string.shop_name), style = MaterialTheme.typography.h6)
h6 스타일은 임의로 준건가요 ?

2024-06-12 13:45 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +            painter = state.storeInfo?.imageUrls?.get(0)
이미지가 하나도 없으면 어떻게 되나요?

2024-06-12 13:45 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +                    .height(screenHeight - 145.dp),
145.dp를 상수로 정의해주세요.

2024-06-12 13:45 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +fun GreetingPreview() {
사용하지 않은 코드는 지워주세요.

2024-06-12 13:45 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +            .verticalScroll(enabled = verticalOffset || scrollState.value != 0, state = scrollState)
remeber과 derivedStateOf을 사용해주세요.

2024-06-12 13:45 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/MenuScreen.kt
> +            .verticalScroll(enabled = verticalOffset || scrollState.value != 0, state = scrollState)
remeber과 derivedStateOf을 사용해주세요.

2024-06-13 12:08 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +fun ScrollView(viewModel: MyStoreDetailViewModel) {
MyStoreScrollScreen으로 변경했습니다!

2024-06-13 12:08 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +    val list = listOf("Test1", "Test2", "Test3","Test4","Test5","Test6","Test7","Test8","Test9","Test10")
넵 테스트용으로 넣어놓은 코드입니다!

2024-06-13 12:11 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +            painter = state.storeInfo?.imageUrls?.get(0)
기본이미지가 나와야합니다..! 수정하겠습니다!

2024-06-13 12:43 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +    LaunchedEffect(expandedItem) {
이벤트 아이템이 펼쳐진 상태에서 recomposable이 되었을 때 아이템이 접혀있는 상태로 유지되게 하는 역할을 합니다!

2024-06-13 14:44 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +            painter = state.storeInfo?.imageUrls?.get(0)
기본 이미지로 보여지게 됩니다!

2024-06-13 15:57 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +                    .height(screenHeight - 145.dp),
수정했습니다!

2024-06-13 15:58 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +fun GreetingPreview() {
수정했습니당

2024-06-13 17:02 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +                Text(text = stringResource(R.string.shop_name), style = MaterialTheme.typography.h6)
일단 임의로 설정해뒀습니다!

2024-06-15 07:21 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +            .verticalScroll(enabled = verticalOffset || scrollState.value != 0, state = scrollState)
반영했습니다!
[73cd42c](https://github.com/BCSDLab/KOIN_ANDROID/pull/282/commits/73cd42ce12f9c8244fadb57a66d6385b9c978c32)

2024-06-17 16:39 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +                Row(modifier = Modifier.padding(vertical = 5.dp)) {
반영했습니당
[73b0295](https://github.com/BCSDLab/KOIN_ANDROID/pull/282/commits/73b02955cbb871d7636d0629581d4fd51cd32647)

2024-06-18 12:46 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +    val expandedItem = List(list.size) { rememberSaveable { mutableStateOf(false) } }
반영했습니당

2024-06-18 14:48 UTC, nayunjae approved these changes

2024-06-18 14:48 UTC, yunjaena approved these changes
수고하셨습니다!

2024-06-19 06:42 UTC, hsgo2430 approved these changes

2024-06-19 06:42 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/store/MenuScreen.kt
> +    Column(
LazyColumn을 사용하면 rememberScrollState() 없이 구현할 수 있을거같네요!

2024-06-19 06:42 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +    val viewModel: MyStoreDetailViewModel = hiltViewModel()
viewModel을 분리하는 연습해보셔서 Preview도 할 수 있게 구현해보세요

2024-06-22 14:32 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MenuScreen.kt
> +    Column(
참고하겠습니다!

2024-06-22 14:32 UTC, merged