[Feature] 사장님 가게 등록 api 연결
BCSDLab/KOIN_ANDROID pull request #299
Opened 2024-06-26 06:21 UTC by hsgo2430

### **개요**
가게 등록 api 연결

---
### **작업 상세내용**
- 가게 이미지 등록시 preSignedUrl을 통해 S3로 이미지 업로드후 fileUrl을 통해 해당 이미지에 접근하도록 구현

- **가게 상세 정보 등록 페이지**
사용자가 등록할 가게의 정보를 최종 확인한 후 다음 버튼을 누르면 API를 이용하여 등록하도록 구현
-<img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/d2757e13-8f33-4190-a434-69d0d5080688 width="150" height="300">

2024-06-26 07:14 UTC, Jokwanhee reviewed
고생했습니다!

S3에 이미지를 업로드할 때는 클라이언트에서 이미지 리사이징을 해주는 것이 좋습니다. S3도 Storage 이기 때문에 용량이 있어 이미지가 많이 업로드되면 용량 초과될 수 있어 요금이 발생해요!
사장님이 이미지를 등록할 때, 핸드폰으로 많이 촬영하실텐데 기본 화질이 높기때문에 1~2MB 가 넘어갑니다. 이렇게 큰 이미지는 클라에서 불러올 때도 한 세월 걸립니다. ㅠㅠ

한 번 비트맵 리사이징에 대해서 공부해보면 좋을 것 같아요 ^^!! 👍

2024-06-26 07:14 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
> +        }
여러가지 이미지 압축 형식을 사용한 이유가 있을까요~? jpg (jpeg) 똑같은 의미입니다. 
예전에 Window 운영체제에서 file extension을 3자를 넘기지 말라고 제한하였기에 JPG가 탄생하게 되었어요! 
(filn extension 은 jpg, jpeg를 의미합니다.)
그래서 mac 에서는 jpg로 저장되게 됩니다.

+ 추가적으로 WEBP 는 deprecated 되었지 않았나용?

2024-06-26 13:49 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
> +        }
맞아요! WEBP는 deprecated 되었어요 그래도 뭔가 압축 형식을 업로드할 이미지의 타입과 맞춰주어야 한다는 생각이 들어서 이미지 타입에 맞는 압축 방식을 사용했어요! .압축형식이 달라도 아무런 이상이 없다면 변경하도록 할게요!

처음에는 
`"image/jpeg" -> bitmap.compress(Bitmap.CompressFormat.JPEG, 100, byteArrayOutputStream)`
이렇게 jpeg만 압축형식을 지정해줬더니 jpg 이미지를 업로드하니까 잘 안되더라구요. 그래서 jpg를 추가로 넣어줬어요.

마지막으로 처음 S3에 이미지를 넣는 작업을 하다보니 이미지 리사이징이라는 생각을 아예 배제하고 구현한거같아요... 한번 이미지 리사이징에 관해 생각해보고 수정하도록 할게요!

2024-06-26 15:34 UTC, yunjaena requested changes
수고했습니다! comment확인해주세요!

2024-06-26 15:34 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreen.kt
> +            .padding(top = paddingTopValue),
modifier를 뚫어놓는게 좋지 않을까요?

2024-06-26 15:34 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
> +        when(mediaType){
bitmap.compress를 Main Thread에서 호출하게 되면 UI가 블로킹 당할 수 있습니다. 작업 스레드에서 호출 되게 변경하는게 좋아보입니다.

2024-06-26 15:34 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
> +    private fun uploadImage(
compress 작업을 viewModel에서 하지 않고 repository에서 작업하는거는 어떨까요?

2024-06-26 15:34 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthViewModel.kt
> +        when(mediaType){
작업 스레드 이슈랑 동일합니다. 그리고 동일하게 compress하는 로직이 들어가면 공통 class나 메서드로 빼주세요.

2024-06-27 11:41 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
> +    private fun uploadImage(
저도 repository에서 compress 작업을 해보고 싶었는데 domain에서는 Bitmap이 android.graphics 경로에 있다보니 선언을 할수가 없더라구요 그래서 repository에서 할 수 없었습니다...

2024-06-27 11:42 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
> +        when(mediaType){
Dispatcher.IO를 사용하여 작업 스레드에서 하도록 하였습니다!

2024-06-27 11:42 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthViewModel.kt
> +        when(mediaType){
넵 알겠습니다!

2024-06-27 11:48 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/finalcheckstore/FinalCheckStoreScreen.kt
> +            .padding(top = paddingTopValue),
헉 뚫어놓겠습니다!

2024-06-27 16:19 UTC, yunjaena requested changes
추가 커멘트 달았습니다 확인해주세요 :)

2024-06-27 16:19 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthViewModel.kt
>          viewModelScope.launch(Dispatchers.IO) {
viewModeScope에서는 웬만해서 Dispatcher를 삽입하지 말고 useCase에서 dispatcher를 Injection 받아서 사용해주세요.

2024-06-27 16:19 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
> +    private fun uploadImage(
byteArrayOutputStream으로 넘겨주면 되지 않나요?

2024-06-27 16:19 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
> +    private fun uploadImage(
그리고 분리된 로직이 안보이는데 확인 부탁합니다!

2024-06-27 16:23 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
> +    private fun uploadImage(
[참고링크](https://tecoble.techcourse.co.kr/post/2023-10-17-image-upload/) 한번 이 아티클을 참고해봐도 좋을 것 같아요

2024-06-29 14:42 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signup/businessauth/BusinessAuthViewModel.kt
>          viewModelScope.launch(Dispatchers.IO) {
넵 Injection받아서 사용하도록 수정하였습니다!

2024-06-29 14:44 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/insertstore/insertmaininfo/InsertBasicInfoScreenViewModel.kt
> +    private fun uploadImage(
uri를 String형식으로 넘겨서 repository에서 UploadImageLocalDataSource를 사용해서 압축하도록 변경하였습니다!

압축로직은 core/upload/ImageUtil이라는 파일로 분리하여 나영님 작업물에도 적용해 놓았습니다!

2024-06-30 07:10 UTC, yunjaena approved these changes
LGTM 수고하셨습니다!

2024-07-01 00:13 UTC, Jokwanhee approved these changes
고생하셨습니다! 👍

2024-07-01 04:24 UTC, merged