Migration Groovy to Kotlin DSL
BCSDLab/KOIN_ANDROID pull request #302
Opened 2024-07-01 09:48 UTC by Jokwanhee

### 요약
- [project, data, domain, core, koin] buildg.gradle 대상으로 진행했습니다.
- Groovy 언어를 Kotlin DSL 로 변경해봤습니다!
- 중복되는 plugin 및 라이브러리 삭제를 했습니다!
- HiltConvetionPlugin 부분이 application 만 사용가능하길래, library 도 사용할 수 있도록 변경했습니다!
- AndroidLibraryConventionPlugin 을 추가했습니다.

아직 부족한 부분이 많아서 검토 한 번 해주시면 감사드리겠습니다..!
toml 라이브러리 쪽 정리하고 싶었는데, conflict 가 많이 날 것 같아서.. 우선 냅뒀습니다.

2024-07-03 08:37 UTC, skdud0629 approved these changes
고생하셨습니당

2024-07-03 12:25 UTC, ThirFir approved these changes
👍👍

2024-07-03 13:32 UTC, yunjaena requested changes
수고했습니다 :) 커멘트 확인해주세요!

2024-07-03 13:32 UTC, yunjaena commented on build.gradle.kts
> +    extra.apply {
build-logic/convention/src/main/java/in/koreatech/convention/AndroidLibrary.kt
파일에 선언했으면 따로 정의 안해도 되는거 아닌가요?

2024-07-03 13:32 UTC, yunjaena commented on data/build.gradle.kts
> +    implementation(libs.hilt.android)
hilt plugin 정의했는데 제거해도 될것 같습니다.

2024-07-03 13:32 UTC, yunjaena commented on domain/build.gradle.kts
> +    implementation(libs.javax.inject)
library 모듈용 플러그인에다가 넣는거는 어떤가요?

2024-07-03 13:32 UTC, yunjaena commented on koin/build.gradle.kts
> +    implementation(platform(libs.firebase.bom))
firebase도 따로 플러그인 만들어서 관리하면 좋을것 같네요

2024-07-04 07:31 UTC, Jokwanhee commented on build.gradle.kts
> +    extra.apply {
[ae54125](https://github.com/BCSDLab/KOIN_ANDROID/pull/302/commits/ae54125bffe2937029b31668a37a45269225aa7b)
해당 커밋으로 AndroidLibrary 에는 targetSdk, compileSdk, minSdk 되어있어서 그 부분 삭제했습니다. 

versionName 과 minVersionCode 는 build.gradle.kts(:koin) 에서 참조하고 있어서 두었습니다. 이 부분을 toml 파일에 옮겨 사용하려 했지만, conflict 우려가 있어 일단 두었습니다!

2024-07-04 07:32 UTC, Jokwanhee commented on data/build.gradle.kts
> +    implementation(libs.hilt.android)
[ae54125](https://github.com/BCSDLab/KOIN_ANDROID/pull/302/commits/ae54125bffe2937029b31668a37a45269225aa7b)
해당 커밋으로 해결했습니다.

2024-07-04 07:32 UTC, Jokwanhee commented on domain/build.gradle.kts
> +    implementation(libs.javax.inject)
그럴경우 domain 모듈에 library convention 플러그인을 추가함으로써, com.android.library 플러그인이 추가되는데 괜찮은건가요..?

2024-07-04 07:59 UTC, Jokwanhee commented on koin/build.gradle.kts
> +    implementation(platform(libs.firebase.bom))
[12f1d63](https://github.com/BCSDLab/KOIN_ANDROID/pull/302/commits/12f1d63b77b00413527b08554eeb464e29c9bef9)
해당 커밋으로 FirebaseConventionPlugin 추가했습니다.

2024-07-04 08:00 UTC, Jokwanhee commented on koin/build.gradle.kts
> +    implementation(platform(libs.firebase.bom))
추가적으로 궁금한 점이 있습니다.
현재 core 모듈에서 firebase analytics 가 사용되어서 analytics 하나의 라이브러리만 종속되어있는데, 이 때문에 core 모듈에 새로만든 firebase convention plugin 을 적용하는 것이 올바른지 아니면 그냥 현재처럼 유지하는 것이 좋을 지.. 저는 후자가 더 나아보이지만 어떻게 생각하시나요..?
(아니면 애초에 analytics 라이브러리가 core 모듈에 있는 것이 이상한 느낌도..)

2024-07-05 07:36 UTC, yunjaena requested changes
리뷰 추가했습니다 :)

2024-07-05 07:36 UTC, yunjaena commented on domain/build.gradle.kts
> +    implementation(libs.javax.inject)
androidLibray가 아니라 java library 일텐데 왜 추가가 되나요?

2024-07-05 07:36 UTC, yunjaena commented on domain/build.gradle.kts
> +    implementation(libs.javax.inject)
libs.javax.inject 를 의미한거였습니다.

2024-07-05 07:36 UTC, yunjaena commented on koin/build.gradle.kts
> +    implementation(platform(libs.firebase.bom))
core에서 :core:analytics로 따로 뺴는게 좋아보여요

2024-07-05 13:54 UTC, Jokwanhee commented on domain/build.gradle.kts
> +    implementation(libs.javax.inject)
[35c00df](https://github.com/BCSDLab/KOIN_ANDROID/pull/302/commits/35c00df1d4ff03a274bf58f968fd6084bc1cbe6f)
해당 커밋으로 JavaLibarayConventionPlugin 추가했습니다.

2024-07-05 14:07 UTC, Jokwanhee commented on koin/build.gradle.kts
> +    implementation(platform(libs.firebase.bom))
now-in-android를 추가적으로 확인해보면서 이해하는데 도움이 되었습니다.
공통으로 사용되는 로직들도 별도로 모듈화(analytics, notification, design system, common ...)하면 너무 좋을 것 같은 생각이 드는데, analyics 작업은 다른 인원이 하고 있어서 안드로이드 회의 때 언급하면서 core 자체 모듈화를 의논 후 작업해봐도 괜찮을까요?

2024-07-08 09:11 UTC, yunjaena commented on koin/build.gradle.kts
> +    implementation(platform(libs.firebase.bom))
네 따로 이슈 파서 진행하시죠

2024-07-08 09:12 UTC, yunjaena approved these changes
LGTM 수고하셨습니다!

2024-07-08 09:20 UTC, merged