Feature/business/store detail
BCSDLab/KOIN_ANDROID pull request #303
Opened 2024-07-02 06:29 UTC by skdud0629

## **개요**
- 사장님 내 상점 페이지
    - 상점 세부 정보, 메뉴 및 이벤트 api 연결
   
## **작업 상세내용**
- 사장님 관련 api를 모아두었던 OwnerApi에서 로그인 인증 토큰이 필요한 부분을 따로 OwnerAuthApi 분리
- coil라이브러리에서 제공하는rememberAsyncImagePainter를 사용해 서버에서 불러온 이미지 uri를 painter로 변환

## **결과 화면**
- 상점 세부 정보
   - <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/665991be-9818-40a2-80ce-4eeb167e53b6 width="150" height="320">
- 상점 메뉴 / 상점 이벤트 
   - <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/da9a0297-b9ab-4b88-ab07-0937379db4cc width="150" height="320"> <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/b95f733a-eb2a-4625-b892-7ec10bc10dae  width="150" height="320"> 
- 이벤트 아이템 펼쳤을 때 
   - <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/c99b663e-79d7-4add-9f05-f1f0f20610ce  width="150" height="230">

## **추후 작업사항**
- 이벤트 수정 및 삭제 구현

2024-07-02 09:17 UTC, yunjaena requested changes
수고하셨습니다! 리뷰 확인해주세요!

2024-07-02 09:17 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +        item.thumbnailImages?.get(0)?.let {
getOrNull 로 하는게 좋아보입니다.

2024-07-02 09:17 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +                .padding(start = 16.dp)
end에다가는 padding을 안줘도 되나요?

2024-07-02 09:17 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +                text = generateOpenCloseTimeString(item.startDate, item.endDate),
무거운 작업이나 연산이 필요한 작업은 remember로 선언하는게 좋습니다.

2024-07-02 09:17 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +                .width(337.dp)
width가 고정 사이즈 인가요?

2024-07-02 09:17 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +fun EventExpandedItem(item: ShopEvent, pagerState: PagerState, onCollapse: () -> Unit = {}) {
ShopEvent가 Stable하나요?

2024-07-02 09:17 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +                text = generateOpenCloseTimeString(item.startDate, item.endDate),
여기도 동일합니다

2024-07-02 09:17 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/MenuScreen.kt
> +    val viewModel: MyStoreDetailViewModel = hiltViewModel()
파라미터로 옮겨주세요

2024-07-02 09:17 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/MenuScreen.kt
> +    val categories = listOf("추천 메뉴", "메인 메뉴", "세트 메뉴", "사이드 메뉴")
stringResource를 사용해주세요.

2024-07-02 09:17 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +        "배달 가능" to state.storeInfo?.isDeliveryOk,
string literal로 관리하면 찾기도 힘들고 나중에 다국어 관리하기도 힘듭니다.

2024-07-02 09:17 UTC, yunjaena commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/GetOwnerShopInfoUseCase.kt
> +class GetOwnerShopInfoUseCase @Inject constructor(
API 에러가 발생하는 경우는 어떻게 처리하나요?

2024-07-03 08:31 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MenuScreen.kt
> +    val categories = listOf("추천 메뉴", "메인 메뉴", "세트 메뉴", "사이드 메뉴")
반영했습니당 
[94ad538](https://github.com/BCSDLab/KOIN_ANDROID/pull/303/commits/94ad5384f579afc5322c393eb898a360892c596a)

2024-07-03 08:39 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
> +        "배달 가능" to state.storeInfo?.isDeliveryOk,
넵 수정했습니당

2024-07-03 12:20 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +        item.thumbnailImages?.get(0)?.let {
수정했습니당

2024-07-03 13:48 UTC, Jokwanhee reviewed
고생하셨습니다. 👍

2024-07-03 13:48 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature/store/MenuScreen.kt
> +        items(4) {
매직넘버 사용하는 것보다는 categories.size 가 더 좋아보입니다!

2024-07-03 13:48 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreDetailScreen.kt
>                      items(3) {
요것도 위와 같습니다.

2024-07-03 13:48 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature/store/MyStoreTopBar.kt
> +            painter = state.storeInfo?.imageUrls?.get(0)
IndexOutOfBoundsException 대응해야할 것 같아요!

2024-07-04 00:29 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +                .width(337.dp)
앗 하나의 디바이스로만 테스트 하다보니 해당 화면에만 맞춰서 사이즈를 줘버렸네요..
여러 디바이스에 대응될 수 있도록 수정했습니다!
[c002e69](https://github.com/BCSDLab/KOIN_ANDROID/pull/303/commits/c002e6921c411da401a053bf0a0bbf07a8df32fd)

2024-07-04 01:05 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MenuScreen.kt
> +        items(4) {
수정했습니당
[257664e](https://github.com/BCSDLab/KOIN_ANDROID/pull/303/commits/257664e7c1604cff0c1b5240efb5fc881da0fb21)

2024-07-04 01:39 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +                text = generateOpenCloseTimeString(item.startDate, item.endDate),
수정했습니다!
[7435fc](https://github.com/BCSDLab/KOIN_ANDROID/pull/303/commits/7435fc77dc22e557e09fae475490f32085ccedc0)

2024-07-04 02:04 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/MenuScreen.kt
> +    val viewModel: MyStoreDetailViewModel = hiltViewModel()
수정했습니당
[2bac78](https://github.com/BCSDLab/KOIN_ANDROID/pull/303/commits/2bac786a17063d62496e8908ee5b3ab72ad67fc5)

2024-07-04 03:56 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +fun EventExpandedItem(item: ShopEvent, pagerState: PagerState, onCollapse: () -> Unit = {}) {
기존에 List로 선언되었던 이벤트, 메뉴 리스트를 immutableList로 변경해서 stable한 형태로 변경했습니다!
[b8f689c](https://github.com/BCSDLab/KOIN_ANDROID/pull/303/commits/b8f689c2cb97f8503764165b51962ca1787bf809)

2024-07-05 12:37 UTC, skdud0629 commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/GetOwnerShopInfoUseCase.kt
> +class GetOwnerShopInfoUseCase @Inject constructor(
토스트 메세지로 어떤 에러가 났는지 알려주고 로그인 화면으로 돌아가도록 처리했습니다!
[b54ed3f(https://github.com/BCSDLab/KOIN_ANDROID/pull/303/commits/b54ed3f1bec6677d6829d42a34ca5520a097fdf4)

2024-07-05 12:42 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/EventScreen.kt
> +                .padding(start = 16.dp)
horizontal로 변경했습니당

2024-07-05 14:29 UTC, Jokwanhee approved these changes
고생하셨습니다 👍

2024-07-05 15:47 UTC, yunjaena approved these changes
LGTM 수고했습니다.

2024-07-05 16:05 UTC, merged