[Feature] 내 상점 페이지 이벤트/공지 수정 삭제
BCSDLab/KOIN_ANDROID pull request #314
Opened 2024-07-07 03:08 UTC by skdud0629

## **개요**
- 사장님 내 상점 페이지
    - 상점 이벤트/공지 수정 및 삭제 구현
   
## **작업 상세내용**
-  이벤트 수정
    - 아이템을 여러 개 선택했을 때 수정 버튼을 누르면 하나의 아이템만 선택할 수 있다는 경고 메세지를 보여줌.
- 이벤트 삭제
    - 다이얼로그로 확인창을 띄운 뒤 삭제
## **결과 화면**
 <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/516a511d-9938-4c64-92bc-466ab50232f3 width="200" height="400">

2024-07-07 12:53 UTC, Jokwanhee reviewed
고생했습니다. 👍

2024-07-07 12:53 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/di/network/AuthNetworkModule.kt
> +                    "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzM4NCJ9.eyJpZCI6NTU0OCwiZXhwIjoxNzE5ODg2Nzc4fQ.5LjbuPxi1G0aQoxtvWjB3ajpd28k6kjjCp4I199fkt3C8cRa40zxcjJwS91X0pSi"
access token 하드코딩으로 넣은 이유가 뭔가요? 테스트하다가 실수로 넣은건가요?

2024-07-07 12:53 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature/store/AppBar.kt
> +fun AppBar(title: String) {
네이밍을 다르게 가져가야할 것 같아요. 공통 컴포넌트라는 네이밍이라 혼동을 야기할 수 있을 것 같습니다.

2024-07-07 12:53 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature/store/OwnerStoreDialog.kt
> +    visibility: Boolean = false
```suggestion
    dialogTitle: String,
    dialogText: String,
    positiveButtonText: String,
    visibility: Boolean = false,
    onConfirmation: () -> Unit,
    onDismissRequest: () -> Unit,
```
composable 함수 매개변수를 다음과 같은 규칙을 지향하여, 개선할 수 있습니다. (정답은 아니고, 이런 규칙을 지향한다..)
**"선택 매개변수 - 필수 매개변수 - 람다"**

2024-07-07 12:53 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature/store/storedetail/event/EventItem.kt
> +    item: ShopEvent, eventOpenCloseTime: String, pagerState: PagerState, onCollapse: () -> Unit = {}
개행 추가해주시면 좋을 것 같습니다

2024-07-07 12:53 UTC, Jokwanhee commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/DeleteOwnerEventsUseCase.kt
> +            throw throwable
예외를 catch 했는데, 왜 또 예외를 던지는 건가요?

2024-07-07 12:53 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature/store/storedetail/event/EventScreen.kt
> +        onDismissRequest = { viewModel.changeDialogVisibility() },
viewModel 메소드를 참조한 람다식 말고 메서드 참조 방식을 하는 것이 불필요한 리컴포지션이 발생하지 않습니다!
```suggestion
        onDismissRequest = viewModel::changeDialogVisibility,
```

2024-07-07 14:29 UTC, yunjaena requested changes
수고 하셨습니다! comment 확인해주세요 :)

2024-07-07 14:29 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/di/network/AuthNetworkModule.kt
> +                    "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzM4NCJ9.eyJpZCI6NTU0OCwiZXhwIjoxNzE5ODg2Nzc4fQ.5LjbuPxi1G0aQoxtvWjB3ajpd28k6kjjCp4I199fkt3C8cRa40zxcjJwS91X0pSi"
절대로 토큰을 commit 하지 마세요. 시크릿 키 포함

2024-07-07 14:29 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailScreen.kt
> +            state.isSelectedEvent.forEach {
forEach로 지우는것이 아닌 viewModel에서 한번에 지우는거는 어떤가요?

2024-07-08 00:56 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/di/network/AuthNetworkModule.kt
> +                    "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzM4NCJ9.eyJpZCI6NTU0OCwiZXhwIjoxNzE5ODg2Nzc4fQ.5LjbuPxi1G0aQoxtvWjB3ajpd28k6kjjCp4I199fkt3C8cRa40zxcjJwS91X0pSi"
테스트하다가 실수로 커밋했습니다..😣

2024-07-10 01:14 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/storedetail/event/EventItem.kt
> +    item: ShopEvent, eventOpenCloseTime: String, pagerState: PagerState, onCollapse: () -> Unit = {}
수정했습니당

2024-07-10 01:14 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/AppBar.kt
> +fun AppBar(title: String) {
AppBar -> OwnerStoreAppBar로 변경했습니다!

2024-07-10 01:58 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/storedetail/event/EventScreen.kt
> +        onDismissRequest = { viewModel.changeDialogVisibility() },
헉 이런 방법이 있었군요..! 감사합니다!😊

2024-07-10 02:05 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailScreen.kt
> +            state.isSelectedEvent.forEach {
뷰모델에서 지우도록 변경했습니다!
[1b7439f](https://github.com/BCSDLab/KOIN_ANDROID/pull/314/commits/1b7439f32672374a7abf73ab241e1eb168a7d313)

2024-07-10 02:32 UTC, skdud0629 commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/DeleteOwnerEventsUseCase.kt
> +            throw throwable
[25a1bd5](https://github.com/BCSDLab/KOIN_ANDROID/pull/314/commits/25a1bd50a115e39d6b35cd94baca8f436febb043)
앗 그러네요 단순 실수같습니다..😥 예외 처리 로직 추가했습니다!

2024-07-10 07:01 UTC, yunjaena approved these changes
LGTM 수고하셨습니다!

2024-07-10 12:39 UTC, Jokwanhee approved these changes
고생하셨습니다 👍

2024-07-10 15:27 UTC, merged