[Feature] 정보 수정 비밀번호 확인 다이얼로그
BCSDLab/KOIN_ANDROID pull request #315
Opened 2024-07-09 08:22 UTC by nodobi

2024-07-10 07:05 UTC, yunjaena requested changes
수고하셨습니다 :) 커멘트 확인해주세요!

2024-07-10 07:05 UTC, yunjaena commented on koin/src/main/java/in/koreatech/koin/ui/userinfo/UserInfoCheckPasswordDialog.kt
> +        binding.tietPassword.removeTextChangedListener(passwordWatcher)
리소스를 해제하는 경우는 super 이전에 하는게 좋아요.
ex) onPause, onStop, onDestroy

2024-07-10 07:05 UTC, yunjaena commented on koin/src/main/java/in/koreatech/koin/util/EventFlow.kt
> +        const val DEFAULT_REPLAY: Int = 3
블로그 글 참고해서 구현한것 같은데 이벤트가 3개 이상 넘어오면 어떻게 핸들하나요?

2024-07-13 05:51 UTC, nodobi commented on koin/src/main/java/in/koreatech/koin/ui/userinfo/UserInfoCheckPasswordDialog.kt
> +        binding.tietPassword.removeTextChangedListener(passwordWatcher)
수정했습니다 감사합니다!
혹시 super 이후에 해제하게 되는 경우 어떤 문제가 발생하는지 알 수 있을까요?

2024-07-13 06:21 UTC, nodobi commented on koin/src/main/java/in/koreatech/koin/util/EventFlow.kt
> +        const val DEFAULT_REPLAY: Int = 3
이벤트가 넘어오는 시점에 따라서 핸들되는 순서가 다소 달라질 것 같습니다.
- EventFlow 를 collect 하고 있는 시점
  - 관련 작업 시행
- collect 하고 있지 않은 경우 (onStop)
  - SharedFlow 의 버퍼에 저장
  - 이후 collect 가 다시 되는 경우 consume 되지 않은 이벤트에 대해 (onStart) 관련 작업 시행

2024-07-15 10:27 UTC, yunjaena commented on koin/src/main/java/in/koreatech/koin/ui/userinfo/UserInfoCheckPasswordDialog.kt
> +        binding.tietPassword.removeTextChangedListener(passwordWatcher)
@nodobi 잘 찾아봤네요 :) 부모 class에서 해제를 할 수도 있기 떄문에 없는 null이거나 이미 리소스가 해제된 것을 해제할 수도 있기 떄문에 조심해야되요!

2024-07-15 10:29 UTC, yunjaena commented on koin/src/main/java/in/koreatech/koin/util/EventFlow.kt
> +        const val DEFAULT_REPLAY: Int = 3
이벤트가 N개 이상 내려올때 이벤트가 유실될 수 있는게 아닐까 싶어서요. 정답은 없지만 해당 부분도 한번 고려 해보면 좋을거 같네요 :)

2024-07-15 10:29 UTC, yunjaena approved these changes
LGTM 수고하셨습니다!

2024-08-04 13:51 UTC, ThirFir approved these changes
수고하셨습니다 !

2024-08-09 12:08 UTC, merged