[Feature] 내 상점 정보 수정 UI
BCSDLab/KOIN_ANDROID pull request #317
Opened 2024-07-09 08:35 UTC by skdud0629

## **개요**
- 사장님 내 상점 수정 페이지
    - 가게 정보 및 운영 시간 변경
   
## **작업 상세내용**
-  가게 상세 정보 수정
    -  radio 버튼으로 배달, 계좌 이체, 카드 가능 여부 선택
- 운영 시간 변경
    - 다이얼로그 안에 HoursNumberPicker 사용
## **결과 화면**
- **정보 수정**
    -  <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/f1f5091d-668f-49c3-b347-0986af8617f7 width="200" height="400">

- **운영시간**
     - <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/3fa2cd8c-d4c2-43db-8759-f4f29071d03b width="200" height="400"> <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/3fa2cd8c-d4c2-43db-8759-f4f29071d03b width="200" height="400"> <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/23f34e29-af72-4989-897f-ed38d837291e width="200" height="400">

## **이슈 사항**
- HoursNumberPicker를 다이얼로그 안에다 넣었을 때 스크롤하면  아이템들이 움직임(?) .
- 다이얼로그 안에 있는 Text의 속성을 `text = "\n\n\n\n\n~",` 이렇게 넣어주니깐 이상한 현상이 사라졌다.. 일단 야메로 해결하긴 했는데 다른 해결 방법을 찾아봐야 될 것 같다..😥
 <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/5e2b1bd4-6bfb-407c-9324-d1f6a320ff61 width="200" height="200"> <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/e7386a1e-de57-4fce-9fd6-711bdc62d9c9 width="200" height="200">

2024-07-09 13:11 UTC, nayunjae requested changes
수고하셨습니다. comment 확인해주세요!

2024-07-09 13:11 UTC, nayunjae commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +    val viewModel: ModifyInfoViewModel = hiltViewModel()
viewModel은 파라미터로 받는것을 추천드립니다! 외부에서 주입을 받을수도 있기 때문이에요

2024-07-09 13:11 UTC, nayunjae commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +            IconButton(onClick = { /*TODO*/ }) {
click 로직이 없으면 TODO는 제거해주세요!

2024-07-09 13:11 UTC, nayunjae commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +                            .height(40.dp), onClick = viewModel::onSettingOperatingTimeClicked ) {
개행 빠졌습니다.

2024-07-09 13:11 UTC, nayunjae commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoState.kt
> +    val dialogTimeState: Pair<FullHours, FullHours> = Pair(FullHours(0, 0), FullHours(0, 0)),
dialogTimeState Pair가 어떤걸 의미하는지를 모르겠네요. 따로 class로 만들어서 묶어보는것은 어떨까요?

2024-07-09 13:11 UTC, nayunjae commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoViewModel.kt
> +                            it[0].toInt(), it[1].toInt()
사이즈 체크 해주세요!

2024-07-09 13:11 UTC, nayunjae commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/OperatingTimeSettingDialog.kt
> +            onDismissRequest = { viewModel.dialogVisibility(-1) },
dialogVisibility(-1) 가아니라 boolean으로 받아야하는게 아닌가요? 아니면 hideAlertDialog() 로 호출하는거는 어떤가요?

2024-07-09 13:11 UTC, nayunjae commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/OperatingTimeSettingDialog.kt
> +                        value = state.operatingTimeList[state.dayOfWeekIndex].openTime.split(":")
: split 하는 로직이 있으면 차라리 hour하고 minute 으로 분리해보는거는 어떨까요?

2024-07-11 05:20 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +            IconButton(onClick = { /*TODO*/ }) {
뒤로가기 로직 추가했습니다!

2024-07-11 05:30 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +                            .height(40.dp), onClick = viewModel::onSettingOperatingTimeClicked ) {
앗 개행 처리하겠습니다

2024-07-11 05:41 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/OperatingTimeSettingDialog.kt
> +            onDismissRequest = { viewModel.dialogVisibility(-1) },
다이얼로그를 띄울 때 요일에 따른 영업 시간을 보여주기 위해 요일 인덱스도 같이 넘겨주도록 했습니다. 그래서 다이얼로그가 dismiss 되었을 때는 인덱스를 받을 필요가 없어서 임의로 -1을 넣어줬습니다..!

말씀하신대로 hideAlertDialog()를 따로 호출해주도록 변경했습니다!
[c3dcc73](https://github.com/BCSDLab/KOIN_ANDROID/pull/317/commits/c3dcc7382a49c9e94deac06f47352f213049e83b)

2024-07-11 07:03 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoState.kt
> +    val dialogTimeState: Pair<FullHours, FullHours> = Pair(FullHours(0, 0), FullHours(0, 0)),
특정 요일의 영업 시간 _( 00:00 ~ 00:00 이런 형식으로 띄워줍니당 )_  을 다이얼로그에 띄우기 위해 따로 다이얼로그에 들어가는 시간을 dialogTimeState로 두었습니다!

데이터 클래스로 묶었습니당
[c9448d4](https://github.com/BCSDLab/KOIN_ANDROID/pull/317/commits/c9448d4d6a125ea4c8a7fd21628c19951e658899)

2024-07-11 09:23 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/OperatingTimeSettingDialog.kt
> +                        value = state.operatingTimeList[state.dayOfWeekIndex].openTime.split(":")
hours와 minutes를 따로 정의하고 있는 FullHours 데이터 클래스를 사용했습니다!
[267348e](https://github.com/BCSDLab/KOIN_ANDROID/pull/317/commits/267348ea610e5f560258dcbd110cc13410c98ad5)

2024-07-11 09:38 UTC, yunjaena approved these changes
LGTM 픽커 이슈는 따로 이슈 생성해서 처리해주세요.

2024-07-12 02:46 UTC, hsgo2430 approved these changes
고생하셨습니다

근데 numberpicker 형태를 아예 바꿔버리셨네요...

이러면 통일을 시켜야해서 작업을 또 해야겠네요...

2024-07-12 02:52 UTC, skdud0629 commented
피그마에 나와있는 ui 그대로 따라가려고 형태를 바꿨습니다..ㅜㅜ

2024-07-12 02:58 UTC, merged