[Feature] 사장님 메뉴가격 등록 UI 생성
BCSDLab/KOIN_ANDROID pull request #318
Opened 2024-07-10 12:11 UTC by hsgo2430

## **개요**
- 사장님 메뉴 가격 등록 UI 생성
   
## **작업 상세내용**
- +가격 추가 버튼을 누르면 추가적인 텍스트 필드가 나오도록 구현
- 라디오 버튼을 눌러서 

## **결과 화면**
- **메뉴 등록 전체 UI**
 <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/1cd6e558-f329-4660-856a-e286f3532cb3 width="200" height="400">

- **스크롤**
<img src= https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/573987a6-4b07-4035-8ee3-2d66f7b74e94 width="200" height="400">

- **동적 텍스트 필드 생성**
<img src= https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/cea22015-aeec-418d-a029-430f93f695f4 width="200" height="400">

- **메뉴 카테고리 라디오버튼**
<img src= https://github.com/BCSDLab/KOIN_ANDROID/assets/89733155/5859ebdc-dba6-4862-b892-5a051324175a width="200" height="400">

## **구현 예정**
- 특정 위치 텍스트 필드 삭제 기능
- 이미지 다중 업로드 기능

2024-07-10 14:44 UTC, yunjaena requested changes
수고하셨습니다 :) 커멘트 확인해주세요~!

2024-07-10 14:44 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
> +                newMenuUriList.add("")
""는 어떤걸 추가해준건가요? 이미지 가 아닌경우 type로 설정하는거는 어떨까요? sealed class ImageHolderType.. 등ImageHolderType.None or ImageHolderType.Sample

2024-07-10 14:44 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
> +                newMenuPrice.add("")
동일합니다.

2024-07-10 14:44 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/textfield/BorderTextField.kt
> +    startPadding: Dp = 10.dp,
paddingValues로 받는거는 어떨까요?

2024-07-10 14:44 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/textfield/BorderTextField.kt
> +    startPadding: Dp = 10.dp,
또는 외부 modifier를 받아서 처리도 가능합니다.

2024-07-11 06:04 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
> +                newMenuUriList.add("")
리스트의 크기를 늘려 뷰에 사용자가 입력할수있는 공간을 나타내기 위해서 add함수를 사용했습니다.

예를들어서 가격추가 버튼을 누르면 add함수를 통해 ""가 추가되어 리스트의 길이가 2가되고 그럼 2개의 텍스트 필드가 사용자의 뷰에 나오록 하였습니다.

그후 사용자가 텍스트를 입력하면 해당 텍스트 필드 위치와 텍스트를 이용해서 ""을 사용자가 입력한 텍스트로 수정하는 방식을 사용했습니다!

최종적으로 저 리스트에 들어갈것은 이미지의 Uri를 String으로 변화시킨 값입니다.

2024-07-11 06:05 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/textfield/BorderTextField.kt
> +    startPadding: Dp = 10.dp,
외부의 modifier를 입력받는 방법을 생각도 못했네요!
말씀하신 방법 두가지 모드 구현해보고 더 나은 방법으로 적용하겠습니다!

2024-07-13 07:56 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/textfield/BorderTextField.kt
> +    startPadding: Dp = 10.dp,
두 가지 방법을 사용했을 땐 외부의 modifier를 받아오는 것보단 paddingValues를 사용하는게 더 적합하다고 생각이 되어 paddingValues를 사용했습니다.

더 나아가 height와 width까지 넣어 사이즈도 조절할 수 있도록 수정해보았습니다!

2024-07-13 14:21 UTC, yunjaena requested changes
커멘트 확인해주세요 :)

2024-07-13 14:21 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/textfield/BorderTextField.kt
> +    height: Dp = 37.dp,
modifier로 값을 받으면 될것 같은데 height를 따로 값을 받은 이유가 있나요?

2024-07-13 14:21 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
> +                val menuCategory = getMenuCategoryUseCase(197)
197은 어떤 숫자인가요? 특별한 의미를 가지고 있으면 따로 상수값으로 표현해주세요.

2024-07-15 00:35 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/textfield/BorderTextField.kt
> +    height: Dp = 37.dp,
테두리를 modifier의 border를 이용해서 그려서 따로 modifier를 가지고 있는게 좋을거라고 생각했습니다

그런데 생각해보니 modifier값 받아오고 추가로 .border을 집어넣어주면 될것같다는 생각이 드네요

확인해보고 수정하겠습니다!

2024-07-15 00:39 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
> +                val menuCategory = getMenuCategoryUseCase(197)
197은 상점의 id입니다.

원래 의도는 사장님이 로그인하면 보유하고 있는 가게가 뜨고 그 중 한 가게를 선택하면 해당 상점의 id를 집어넣으려고 하였습니다

하지만 지금은 구현되어있지 않으니 임시로 197이라는 상점 아이디를 강제로 넣은것입니다

그런데 저 숫자의 의미는 저만 알고있고 나중에 수정해야하는 부분이니
임시로 val shopId = 197를 선언해서 넣어놓겠습니다!

2024-07-15 10:34 UTC, nayunjae approved these changes
LGTM 수고하셨습니다 :)

2024-07-15 10:34 UTC, yunjaena approved these changes

2024-07-15 12:34 UTC, skdud0629 approved these changes
고생하셨어요👍

2024-07-17 04:02 UTC, merged