[Feature] 내 상점 정보 수정 api 연동
BCSDLab/KOIN_ANDROID pull request #322
Opened 2024-07-16 01:25 UTC by skdud0629

## **개요**
- 사장님 내 상점 수정 페이지
    - 가게 정보 및 운영 시간 변경 api 연동
   
## **작업 상세내용**
-  가게 상세 정보 수정
    -   LaunchedEffect의 키값을 storeInfo로 할당함으로써 가게 정보를 수정되었을 때 현재 상점 페이지에 수정된 정보를 반영함
## **결과 화면**
- <img src=https://github.com/user-attachments/assets/6752fa25-ff10-449c-9f5b-0b4917e4ee9b width="200" height="400">

## **추후 작업 사항**
- 상점 대표 이미지 수정 (다중 이미지 업로드)

2024-07-16 05:37 UTC, yunjaena requested changes
수고했습니다 :) 최대한 viewModel 호출은 최상단에서 호출해주세요. viewModel이 종속되버리면 composable을 재활용하기 어려워집니다!

2024-07-16 05:37 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +    if (isInit.value) {
isInit을 여기서 체크하지 말고 viewModel에서 init할 경우 처리하는 것은 어떤가요?

2024-07-16 05:37 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyOperatingTimeScreen.kt
> +                viewModel = viewModel,
setting Dialog에서 viewModel의 의존을 가지고 있는 것보다는 callback을 통해서 핸들링 하는게 좋아보입니다.
dialog 재활용 측면

2024-07-16 05:37 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreTopBar.kt
>  fun CollapsedTopBar(
viewModel의 로직은 최상단에서 핸들링하는게 좋습니다.

2024-07-16 05:37 UTC, yunjaena commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/GetOwnerShopInfoUseCase.kt
> +    ): Pair<StoreDetailInfo?, ErrorHandler?> {
ErrorHandler 보다 Result를 사용해보는것은 어떨까요?

2024-07-16 06:26 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreTopBar.kt
>  fun CollapsedTopBar(
수정했습니다!
[5493b19](https://github.com/BCSDLab/KOIN_ANDROID/pull/322/commits/5493b1950a2e0593086eca199687b28a6d4fd375)

2024-07-16 07:06 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyOperatingTimeScreen.kt
> +                viewModel = viewModel,
재활용에 대해 생각하고 코드를 막 짜다보니 뷰모델에 의존되는 composable이 많아졌네요😔 다음에는 이런 부분 신경써서 작성하겠습니다! 감사합니다!

[deb6f49](https://github.com/BCSDLab/KOIN_ANDROID/pull/322/commits/deb6f49bb2e4a563fc57fc26d0503028baa1a29d)

2024-07-16 07:51 UTC, skdud0629 commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/GetOwnerShopInfoUseCase.kt
> +    ): Pair<StoreDetailInfo?, ErrorHandler?> {
수정했습니다!
[b1a94c7](https://github.com/BCSDLab/KOIN_ANDROID/pull/322/commits/b1a94c70fde6f8d768e4fe99965a136cfc286df2)

2024-07-16 09:27 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +    if (isInit.value) {
다른 뷰모델의 state값을 인자로 받아서 init으로 처리할 수 없었습니다..ㅜㅜ 
초기 값을 한 번만 받아와야 되기 때문에 일단 이전 화면의 LaunchedEffect에서 초기화하는 로직으로 변경했습니다

[c16173b](https://github.com/BCSDLab/KOIN_ANDROID/pull/322/commits/c16173b0db5235ef032937f0663696aaa6cee610)

2024-07-17 02:20 UTC, yunjaena requested changes
수고했습니다 :) 커멘트 확인해주세요.

2024-07-17 02:20 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyOperatingTimeScreen.kt
> +                state.storeInfo.operatingTime.forEachIndexed { index, item ->
items에서 변경한 이유가 있나요?

2024-07-17 02:24 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyOperatingTimeScreen.kt
> +                state.storeInfo.operatingTime.forEachIndexed { index, item ->
딱히 변경한 이유는 없습니다..!

2024-07-17 03:25 UTC, nayunjae commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyOperatingTimeScreen.kt
> +                state.storeInfo.operatingTime.forEachIndexed { index, item ->
그러면 여기서는 composable을 생성하는것이기 때문에 items 가 더 맞지 않을까요? 지금은 리스트가 얼마 안되서 성능상의 이슈가 없을수 있겠지만 리스트가 100개 1000개 정도 되면 버벅이는게 심해집니다.

2024-07-17 03:29 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyOperatingTimeScreen.kt
> +                state.storeInfo.operatingTime.forEachIndexed { index, item ->
넵 itemsIndexed로 수정했습니다!

2024-07-17 03:35 UTC, yunjaena approved these changes
LGTM 수고하셨습니다!

2024-07-17 04:03 UTC, hsgo2430 approved these changes
완전 고생하셨어요! 이제 얼마 안남았으니 조금더 힘내요!

2024-07-17 05:11 UTC, merged