[Feature] 내 상점 수정 페이지 다중 이미지 업로드
BCSDLab/KOIN_ANDROID pull request #331
Opened 2024-07-19 04:05 UTC by skdud0629

## **개요**
- 사장님 내 상점 수정 페이지
    - 가게 대표 이미지 업로드 
   
## **작업 상세내용**
- 다중 이미지 업로드
    -  photo picker & presigned url 사용

## **결과 화면**
- <img src=https://github.com/user-attachments/assets/7eb6a2cc-b12e-4050-b561-e70474101257 width="200" height="400">

2024-07-19 06:15 UTC, yunjaena requested changes
수고하셨습니다 :) comment 확인해주세요!

2024-07-19 06:15 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +                val cursor = context.contentResolver.query(it, null, null, null, null)
query하는 Main thread에서 작업하는게 무거울 수  있습니다. worker thread에서 작업하도록 변경해주세요 :)

2024-07-19 06:15 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +                val cursor = context.contentResolver.query(it, null, null, null, null)
사진 관리하는 화면이 많으면 따로 클래스로 빼서 작업해보는것도 좋아보이네요

2024-07-22 02:34 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +                val cursor = context.contentResolver.query(it, null, null, null, null)
이미지 처리 로직 따로 분리해주고 worker thread에서 작업하도록 변경했습니다!
[751eaf1](https://github.com/BCSDLab/KOIN_ANDROID/pull/331/commits/751eaf19018b1a6f89dedc019072c56c17cc30d9)
[c81e005](https://github.com/BCSDLab/KOIN_ANDROID/pull/331/commits/c81e00569683d0e485e17ca3068c393582283260)

2024-10-29 02:32 UTC, yunjaena approved these changes
LGTM 수고하셨습니다.

2024-10-29 02:40 UTC, hsgo2430 approved these changes
고생하셨어요!

2024-10-30 12:45 UTC, merged