[Feature] 사장님 메뉴 가격 및 이미지 등록
BCSDLab/KOIN_ANDROID pull request #355
Opened 2024-08-19 10:33 UTC by hsgo2430

## **개요**
- 메뉴 가격 등록
- 메뉴 이미지 등록
   
## **결과 화면**
- 메뉴 가격 등록
<img src=https://github.com/user-attachments/assets/089aba98-50cd-4f0a-9895-05e364d62916 width="200" height="400">

- 리뷰 수정/삭제
<img src=https://github.com/user-attachments/assets/167654ef-f8f4-436c-87dd-31d831b68f0e  width="200" height="400">

2024-08-19 15:28 UTC, yunjaena requested changes
수고했습니다 :) comment 확인해주세요.

2024-08-19 15:28 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
> +                if(uriList.size < 3){
최대 갯수를 상수로 정의해주세요.

2024-08-19 15:28 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
> +                    for(imageUri in uriList)
uriList.size -1 만큼 추가하면 되는게 아닌가요?

2024-08-19 15:28 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/InsertMenuScreen.kt
> +            BasicTextField(
동일한 디자인인것 같은데 따로 빼주는것은 어떤가요?

2024-08-20 03:37 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
> +                if(uriList.size < 3){
넵 상수로 정의하겠습니다!

2024-08-20 03:45 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
> +                    for(imageUri in uriList)
newMenuUriList에는 [A, Uri.EMPTY]
uriList에는 [B, C] 이렇게 있는 경우
newMenuUriList에는 removeAt을 해서 [A]만 남겨두고 
for를 사용해서 uriList의 값을 newMenuUriList에 넣는 방식입니다!

2024-08-20 04:00 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/InsertMenuScreen.kt
> +            BasicTextField(
MenuBorderTextField라는 컴포저블 함수를 따로 만들어서 빼겠습니다!

2024-08-20 05:12 UTC, yunjaena approved these changes
LGTM 수고하셨습니다 !

2024-08-20 06:31 UTC, skdud0629 approved these changes
수고하셨습니다! 👍

2024-08-20 06:54 UTC, merged