[Feature] 사장님 회원가입 페이지
BCSDLab/KOIN_ANDROID pull request #356
Opened 2024-08-20 01:36 UTC by skdud0629

### **개요**

사장님 회원가입 페이지 수정
- 기본정보 입력/사업자 인증 페이지 수정

---
### **작업 상세내용**
- 메일 인증에서 문자 인증으로 바뀜에 따라 개인 번호를 입력받는 부분을 삭제함.
-  회원가입 요청 api 변경 (메일 인증 전용 회원가입 요청 api 와 다른 api 사용 )
- 전화번호 및 사업자 번호 중복 체크 api 연결

**기본 정보 입력**
- 전화번호 중복 체크
- <img src=https://github.com/user-attachments/assets/b6a86b39-7536-41e5-8500-0cc46a80c77b width="200" height="360"> 

**사업자 인증**
- 사업자 번호 중복 체크 및 화면 구성 변경
변경 전 후 화면
- <img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/ca0d6b17-9b40-4283-af8d-f277cc914c3e width="200" height="360"> <img src=https://github.com/user-attachments/assets/e39ba7f0-edd2-40ce-a75d-ef7a7c0647fe width="200" height="360">

2024-08-20 04:57 UTC, yunjaena requested changes
수고했습니다 :) comment 확인해주세요 :)

2024-08-20 04:57 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupScreen.kt
> +                enabled = state.isButtonEnabled && state.verifyState == SignupContinuationState.CheckComplete,
isButtonEnable state에 verifyState 검사랑 같이 들어가야되지 않을까요?

2024-08-20 04:57 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupViewModel.kt
> +                            )
error 가 null일때 return 해주세요.

2024-08-20 07:02 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupScreen.kt
> +                enabled = state.isButtonEnabled && state.verifyState == SignupContinuationState.CheckComplete,
수정했습니다! 
[1867f7e](https://github.com/BCSDLab/KOIN_ANDROID/pull/356/commits/1867f7e422c0375e0e249b8d0e9a384361fe23bf)

2024-08-20 07:06 UTC, skdud0629 commented on business/src/main/java/in/koreatech/business/feature/signup/accountsetup/AccountSetupViewModel.kt
> +                            )
기존에 있던 inline 함수를 적용해 오류를 처리하도록 변경했습니다!
[d4d6a87](https://github.com/BCSDLab/KOIN_ANDROID/pull/356/commits/d4d6a87d911a81a01ccae464262ff81fcd17fc7a)

2024-08-20 07:32 UTC, nayunjae approved these changes
LGTM 수고했습니다 :)

2024-08-20 07:33 UTC, yunjaena approved these changes
LGTM 수고했습니다 :)

2024-08-21 13:57 UTC, hsgo2430 approved these changes
고생하셨엉요!!

2024-08-21 14:22 UTC, merged