[Feature] 사장님 가게 메뉴 등록 기능 구현
BCSDLab/KOIN_ANDROID pull request #358
Opened 2024-08-22 07:22 UTC by hsgo2430

## **개요**
- 사장님 메뉴 등록 전 체크 화면 생성
   
- 확인 버튼 클릭 시 이미지 다중 업로드 및 메뉴 내용 업로드
   
## **결과 화면**
- 가격이 1개일 때 화면
<img src= https://github.com/user-attachments/assets/a718b34a-5c9f-4bb7-b34c-02d4f8064c96 width="200" height="400">

- 가격이 여러개 일때 화면
<img src= https://github.com/user-attachments/assets/df09f4f2-c051-4e6d-a91c-5aafc5a27683 width="200" height="400">

2024-08-23 11:50 UTC, nayunjae requested changes
수고하셨습니다 리뷰 해주세요 ~!

2024-08-23 11:50 UTC, nayunjae commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuCheckScreen.kt
> +    onPositiveButtonClicked: () -> Unit= {}
```suggestion
    onPositiveButtonClicked: () -> Unit = {}
```

2024-08-23 11:50 UTC, nayunjae commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
> +                val storeId = 163
임시 ID인가요? TODO 로 표시해주면 좋을것 같습니다.

2024-08-23 11:50 UTC, nayunjae commented on data/src/main/java/in/koreatech/koin/data/repository/OwnerRegisterRepositoryImpl.kt
> +            Result.success(Unit)
EOFException이 성공인가요?

2024-08-23 11:52 UTC, hsgo2430 commented on data/src/main/java/in/koreatech/koin/data/repository/OwnerRegisterRepositoryImpl.kt
> +            Result.success(Unit)
아아  코딩할때 순간 미쳤었나보네요... 수정하겠습니다!

2024-08-23 11:52 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuCheckScreen.kt
> +    onPositiveButtonClicked: () -> Unit= {}
아이고... 수정하겠습니다!

2024-08-23 11:54 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/registermenu/registermenu/RegisterMenuViewModel.kt
> +                val storeId = 163
맞습니다! 까먹지 않도록 TODO로 표시하겠습니다!

2024-08-23 11:54 UTC, hsgo2430 commented on data/src/main/java/in/koreatech/koin/data/repository/OwnerRegisterRepositoryImpl.kt
> +            Result.success(Unit)
순간 정신줄을 놨나봅니다.. 수정하도록하겠습니다

2024-08-23 12:01 UTC, yunjaena approved these changes
LGTM 수고하셨습니다!

2024-08-24 04:02 UTC, skdud0629 approved these changes
수고하셨어요!

2024-08-24 04:18 UTC, merged