[Feature] 사장님 비밀번호 변경 예외 처리
BCSDLab/KOIN_ANDROID pull request #359
Opened 2024-08-24 09:58 UTC by skdud0629

## **개요**
- 사장님 비밀번호 변경 페이지
    - 에러 메시지 표시 방식 변경
   
## **작업 상세내용**
- 기존에 토스트 메세지로 나오던 에러 메세지를 textfield 아래에 나오도록 변경

## **결과 화면**
- 계정 인증
  - <img src=https://github.com/user-attachments/assets/a8d7e9a8-6e9b-489a-ab2b-d1b64ae8f17b width="180" height="400"> <img src=https://github.com/user-attachments/assets/1c574edd-81e5-44c9-a23d-6786553326a2 width="180" height="400">

- 비밀번호 변경
   -<img src=https://github.com/user-attachments/assets/c10a483b-113d-4178-aa00-3538a3d808aa width="180" height="400"> <img src=https://github.com/user-attachments/assets/d09cde19-49f2-4bf6-90bf-5372ac66e769 width="180" height="400">

[피그마](https://www.figma.com/design/tDCzPQyt4AeWSW7937T10a/KOIN-Mobile?node-id=1-20479&t=6U3PlGB2XH77nu83-0)

2024-08-24 12:39 UTC, yunjaena requested changes
계정인증 버튼 간격이 디자인과 상의 합니다. 확인 부탁드립니다.

2024-08-24 12:46 UTC, yunjaena requested changes

2024-08-24 12:46 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/findpassword/changepassword/ChangePasswordScreen.kt
> +                modifier = modifier.padding(start = 8.dp, bottom = 8.dp, top = 29.dp),
```suggestion
                modifier = Modifier.padding(start = 8.dp, bottom = 8.dp, top = 29.dp),
```

2024-08-27 13:40 UTC, yunjaena requested changes

2024-08-27 13:40 UTC, yunjaena commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/changepassword/SendAuthSmsCodeUseCse.kt
> +            null to ownerErrorHandler.handleFindPasswordError(t)
Result.Failure 로 안한 이유가 있나요?

2024-08-27 14:08 UTC, skdud0629 commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/changepassword/SendAuthSmsCodeUseCse.kt
> +            null to ownerErrorHandler.handleFindPasswordError(t)
Pair의 두 번째 값(ErrorHandler)에서 에러를 반환하고 있기 때문에 굳이 Result.Failure 로 에러를 명시하지 않아도 된다고 생각해서 null로 설정했습니다!

2024-08-27 14:47 UTC, nayunjae commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/changepassword/SendAuthSmsCodeUseCse.kt
> +            null to ownerErrorHandler.handleFindPasswordError(t)
그러면 Result를 사용할 필요가 없지 않나요

2024-08-28 00:54 UTC, skdud0629 commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/changepassword/SendAuthSmsCodeUseCse.kt
> +            null to ownerErrorHandler.handleFindPasswordError(t)
앗 그러네요 수정했습니다!
[db06d1d](https://github.com/BCSDLab/KOIN_ANDROID/pull/359/commits/db06d1dc68c03796639ff964ca01834d929e3a9a)

2024-08-28 01:20 UTC, nayunjae requested changes

2024-08-28 01:20 UTC, nayunjae commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/changepassword/SendAuthSmsCodeUseCse.kt
> +            null to ownerErrorHandler.handleFindPasswordError(t)
Result.Failure Exception에 type을 줘서 해결하면 되지 않을까요?
HandlePasswordFailureException: Exception()

2024-08-28 06:42 UTC, skdud0629 commented on domain/src/main/java/in/koreatech/koin/domain/usecase/business/changepassword/SendAuthSmsCodeUseCse.kt
> +            null to ownerErrorHandler.handleFindPasswordError(t)
수정했습니다!

[5f69f19](https://github.com/BCSDLab/KOIN_ANDROID/pull/359/commits/5f69f1907c38f78527949f1661e21ef681740a65)

2024-08-28 06:48 UTC, yunjaena approved these changes
LGTM 수고하셨습니다!

2024-08-28 08:30 UTC, hsgo2430 approved these changes
고생하셨습니다!

2024-08-28 08:35 UTC, merged