[Feature] 메뉴 데이터 가져와서 수정하는 기능 추가
BCSDLab/KOIN_ANDROID pull request #361
Opened 2024-08-28 07:30 UTC by hsgo2430

## **개요**
- 메뉴 수정 UI 생성
    - API를 통해 등록된 메뉴 데이터 가져옴
    
   
## **결과 화면**
- 메뉴 수정 UI
<img src=  https://github.com/user-attachments/assets/40630945-7a1b-4601-b138-9ebfb99ef582 width="250" height="400">

2024-08-28 08:52 UTC, yunjaena requested changes
수고했습니다! comment 확인해주세요!

2024-08-28 08:52 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuScreen.kt
> +    menuId: Int = 2796,
shopId랑 menuId를 파라미터로 전달하나요? viewModel에서 전달받는거는 어떤가요?

2024-08-28 08:52 UTC, yunjaena commented
conflict도 확인해주세요!

2024-08-28 10:47 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuScreen.kt
> +    menuId: Int = 2796,
해당 파라미터는 viewModel에서 메뉴 데이터를 가져오기 위해서만 사용하고 Screen 자체에서는 사용하지 않습니다. 그래서 뷰모델로 전달하기 위해서 Screen에서 파라미터로 받고 `viewModel.settingId(shopId, menuId)`를 이용해서 뷰모델로 전달하는 방향으로 구현하였습니다.

2024-08-28 11:15 UTC, yunjaena requested changes

2024-08-28 11:15 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuScreen.kt
> +    menuId: Int = 2796,
이렇게 되면 recompostion 될떄마다 호출이 되는데 확인해봤나요?

2024-08-28 13:56 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuScreen.kt
> +    menuId: Int = 2796,
로그 찍어서 확인해보니까 recomposition이 나올때마다 호출되네요... 다른 방법을 찾아봐야겠어요...

2024-09-04 11:50 UTC, yunjaena approved these changes
수고하셨습니다!

2024-09-05 03:58 UTC, skdud0629 approved these changes
수고하셨어요!

2024-09-05 04:08 UTC, merged