[Feature] 사장님 메뉴 수정기능 추가
BCSDLab/KOIN_ANDROID pull request #374
Opened 2024-09-06 07:11 UTC by hsgo2430

## **개요**
- 메뉴 수정기능 추가
    - 메뉴 수정전 마지막으로 확인하는 UI 구현
    - 확인 버튼 누르면 메뉴가 수정되도록 구현
    
   
## **결과 화면**
- 메뉴 수정 과정
<img src= https://github.com/user-attachments/assets/551549b0-cd3f-412c-8e19-5eb0d658ef72 width="250" height="400">

2024-09-06 09:10 UTC, yunjaena requested changes
수고했습니다! 리뷰 확인해주세요.

2024-09-06 09:10 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuViewModel.kt
> +                            val cursor = context.contentResolver.query(uri, null, null, null, null)
query는 무거운 작업입니다. background에서 해주세요

2024-09-06 09:10 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuViewModel.kt
> +                            val cursor = context.contentResolver.query(uri, null, null, null, null)
공통 로직이 있으면 빼보는것도 방법일것 같습니다.

2024-09-06 09:10 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuCheckScreen.kt
> +            item {
아이템이 너무 복잡하면 LazyColumn scope을 확장함수로 만들어서 section으로 분리해보세요

2024-09-06 09:10 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuCheckScreen.kt
> +                onClick = { onBackPressed }
onBackPressed() 아닌가요?

2024-09-06 09:10 UTC, yunjaena commented on data/src/main/java/in/koreatech/koin/data/repository/OwnerRegisterRepositoryImpl.kt
> +        } catch (e: EOFException) {
모든 exception을 catch할꺼면 runcatching을 사용한후 CancellationException인 경우 throw 해주세요!

2024-09-09 14:07 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuViewModel.kt
> +                            val cursor = context.contentResolver.query(uri, null, null, null, null)
공통으로 사용하는 부분이 있어서 로직을 함수화 하였고 background에서 작동하도록 수정하였습니다!

2024-09-09 14:08 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuCheckScreen.kt
> +            item {
CheckMenuComponent을 만들어서 확장함수로 구현해보았습니다!

2024-09-09 14:08 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuCheckScreen.kt
> +                onClick = { onBackPressed }
헉... 어쩐지 안먹더라니 저런 실수가 있었네요... 수정하겠습니다.!

2024-09-09 14:08 UTC, hsgo2430 commented on data/src/main/java/in/koreatech/koin/data/repository/OwnerRegisterRepositoryImpl.kt
> +        } catch (e: EOFException) {
runcatching이라는 것도 있었군요.... 적용해보겠습니다!

2024-09-09 14:20 UTC, yunjaena requested changes

2024-09-09 14:20 UTC, yunjaena commented on data/src/main/java/in/koreatech/koin/data/repository/OwnerRegisterRepositoryImpl.kt
> +        }.onFailure {exception ->
onSuccess 블록은 없어도 되나요?

2024-09-09 14:28 UTC, yunjaena approved these changes
LGTM 수고했습니다!

2024-09-17 02:08 UTC, skdud0629 approved these changes
수고했어요!

2024-09-17 02:17 UTC, merged