[Feature] 사장님 로그인 기능 구현
BCSDLab/KOIN_ANDROID pull request #378
Opened 2024-09-13 09:38 UTC by hsgo2430

### **개요**

>-----------------

- 사장님 로그인 기능 구현

### **상세 작업 내용**
>-----
- 사장님 로그인 기능 추가
- 사장님 로그인 아이디 전화번호로 변경
-  로그인 UI를 웹 UI와 동기화
- 오류 메시지를 textfield 아래에 나오도록 변경

### **작업 결과물**
- 로그인 화면
<img src= https://github.com/user-attachments/assets/50001f26-5740-4149-9ec4-bfcf145d4c46 width="250" height="500">

- 아이디 빈칸
<img src=  https://github.com/user-attachments/assets/7cf349c7-cc57-4a61-987a-a84310f849ed width="250" height="500">

-  비밀번호 빈칸
<img src=  https://github.com/user-attachments/assets/8efa3218-85dc-407c-8b58-bcc47e9448f5 width="250" height="500">

- 틀린 비밀번호
<img src=   https://github.com/user-attachments/assets/ec961219-75a5-4789-9da2-8a4c9855a4ca  width="250" height="500">

2024-09-13 14:21 UTC, yunjaena requested changes
로그인 버튼과 회원가입 버튼 사이 간격이 넓어 보이는데 확인 부탁드립니다!

2024-09-13 14:21 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInViewModel.kt
> +            }
ShowNullMessage 보다 ShowErrorMessage가 낫지 않을까요?

2024-09-13 14:21 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            password -> viewModel.insertPassword(password)
```suggestion
            password -> viewModel::insertPassword
```

2024-09-13 14:21 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/signin/SignInViewModel.kt
> +    private fun toastErrorMessage(message: String) = intent {
```suggestion
    private fun showErrorMessage(message: String) = intent {
```
나중에 toast가 될수도 있고  snackbar이 될수도 있으니 범용적으로 메소드 명을 짓는거는 어떨까요?

2024-09-16 12:03 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            password -> viewModel.insertPassword(password)
이런 방법이 있었군요...!
한번 공부를 해봐야겠어요!

2024-09-16 12:03 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInViewModel.kt
> +            }
바꾸는걸 깜빡했네요... 수정하겠습니다!

2024-09-16 12:03 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInScreen.kt
> +            password -> viewModel.insertPassword(password)
이런 방법이 있군요...
한번 공부를 해봐야겠네요!

2024-09-16 12:03 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/signin/SignInViewModel.kt
> +    private fun toastErrorMessage(message: String) = intent {
수정했어야 했는데 깜빡했나보네요 감사합니다!

2024-09-16 15:50 UTC, yunjaena approved these changes
LGTM 수고했습니다!

2024-09-17 02:08 UTC, skdud0629 approved these changes
수고하셨어요!

2024-09-17 02:18 UTC, merged