메뉴 등록 및 수정 기능에서 카메라 촬영 기능 추가
BCSDLab/KOIN_ANDROID pull request #389
Opened 2024-09-25 03:38 UTC by hsgo2430

### **개요**

>-----------------
- 메뉴 등록 및 수정 시 카메라 촬영 기능 구현

### **상세 작업 내용**
>-----
- ActivityResultContracts.TakePicture()를 사용하여 이미지 촬영 후 등록

### **작업 결과물**
- 이미지 촬영 후 등록
<img src= https://github.com/user-attachments/assets/b924d9ab-5cf4-4739-94e8-fe8bd6bbcff0 width="250" height="500">

2024-09-25 06:19 UTC, yunjaena requested changes
수고하셨습니다! comment  확인해주세요

2024-09-25 06:19 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/navigation/BusinessNavHost.kt
> +        startDestination = if(accessToken != EMPTYTOKEN) MYSTORESCREEN else SIGNINSCREEN,
token을 직접 가져오는것이 아니라 MainActivity에서 상태를 가져와서 처리하는게 좋아보입니다.

2024-09-25 06:25 UTC, Jokwanhee reviewed
오랜만에 코드 리뷰 다네요~ 자주 오겠습니다~ 고생했어요~ ☺️

2024-09-25 06:25 UTC, Jokwanhee commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuScreen.kt
> +            viewModel.menuImageFromCamera(it)
람다식과 메소드 참조에 대해서 알아보면 좋을 것 같습니다~

리컴포지션 성능 측면에서 고려해볼 수 있는 부분이 있어요~
https://tech.wonderwall.kr/articles/recomposition/

2024-09-25 06:25 UTC, Jokwanhee commented on core/src/main/java/in/koreatech/koin/core/upload/ImageUtil.kt
> +    return contentResolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, content)
File 유틸 클래스 만들어서 추상화해도 괜찮을 것 같은데 같은데, 어떠시오? 🤠

2024-09-26 03:32 UTC, hsgo2430 commented on core/src/main/java/in/koreatech/koin/core/upload/ImageUtil.kt
> +    return contentResolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, content)
추상화.... 한번 만들어볼게요!

2024-09-26 03:33 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/navigation/BusinessNavHost.kt
> +        startDestination = if(accessToken != EMPTYTOKEN) MYSTORESCREEN else SIGNINSCREEN,
한번 시도해보겠습니다!

2024-09-26 03:34 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/storemenu/modifymenu/modifymenu/ModifyMenuScreen.kt
> +            viewModel.menuImageFromCamera(it)
윤재님에 이어서 관희형까지 언급하시는걸 보니 제대로 공부해봐야겠네요!

2024-09-26 05:42 UTC, Jokwanhee approved these changes
리뷰 코멘트가 학습 코멘트라 미리 어프로브 해놓을게요~ 고생많았다요~ ☺️

2024-09-26 15:45 UTC, yunjaena requested changes
vi

2024-09-26 15:45 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/BusinessMainActivity.kt
> +    lateinit var userRepository: UserRepository
viewModel을 사용하는거는 어떤가요?

2024-09-27 07:03 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/BusinessMainActivity.kt
> +    lateinit var userRepository: UserRepository
역시 뷰모델을 사용하는게 나은가보네요...
뷰모델에서 해보겠습니다!

2024-09-29 13:58 UTC, yunjaena approved these changes
LGTM 수고하셨습니다.

2024-09-30 03:28 UTC, ThirFir commented
요거 머지하실거라면 3.6.0 배포 후에 머지해주시면 감사드리겠습니다 ! (현재 이슈로 배포가 야악간 지연됐는데 금방 해결할게요)

2024-10-02 03:51 UTC, merged