[Feature]가게 선택 다이얼로그 생성
BCSDLab/KOIN_ANDROID pull request #401
Opened 2024-10-02 09:06 UTC by hsgo2430

### **개요**

>-----------------
- 가게 선택 다이얼로그 생성

### **상세 작업 내용**
>-----
-  Dialog 컴포저블을 이용하여 커스텀 다이얼로그 생성
-  가게 선택 시 해당 가게 데이터 가져오도록 수정

### **작업 결과물**

- 다이얼로그
<img src= https://github.com/user-attachments/assets/124f2387-6ec0-4e7f-b89c-dbf9dc91081e width="250" height="500">

- 가게 선택 작동
<img src= https://github.com/user-attachments/assets/066c3f1c-1e42-4bae-a69b-00ea73410957 width="250" height="500">

2024-10-02 15:23 UTC, yunjaena requested changes

2024-10-02 15:23 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/storedetail/dialog/MyStoreSelectDialog.kt
> +fun PreviewMyStoreSelectDialog() {
```suggestion
private fun PreviewMyStoreSelectDialog() {
```

2024-10-02 15:23 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailState.kt
> +    val isEditMode: Boolean = false,
```suggestion
    val isEditMode: Boolean = false
```

2024-10-02 15:23 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/storedetail/MyStoreDetailScreen.kt
> +        viewModel.changeMyStoreInfo(storeId = state.storeId)
viewModel에서 변경할수있는 로직같습니다. 확인해주세요

2024-10-06 13:02 UTC, yunjaena requested changes
리뷰 확인해주세요~!

2024-10-06 13:02 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +                onModifyButtonCLicked()
```suggestion
                onModifyButtonClicked()
```

2024-10-06 13:02 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +                storeInfoViewModel.modifyStoreInfo(state.storeInfo)
modify가 완료가 되고 refresh를 해야되는게 아닌가요? (실패했을경우?)

2024-10-08 09:15 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoScreen.kt
> +                storeInfoViewModel.modifyStoreInfo(state.storeInfo)
그래서 뷰모델에서 
```
modifyInfoUseCase.invoke(
                    storeId,
                    storeDetailInfo,
                ).apply {
                    this ?: postSideEffect(ModifyInfoSideEffect.NavigateToMyStoreScreen)
                }    
```
이 코드를 통해 ErrorHandler가 null일 때 ModifyInfoSideEffect.NavigateToMyStoreScreen를 보내는 것으로 구현했습니다!

2024-10-09 16:22 UTC, yunjaena approved these changes
LGTM 수고하셨습니다!

2024-10-17 12:13 UTC, skdud0629 approved these changes
수고하셨어요!

2024-10-17 12:14 UTC, merged