[Fix]number picker UI 변경 버그 수정
BCSDLab/KOIN_ANDROID pull request #437
Opened 2024-10-27 01:32 UTC by hsgo2430

## **개요**
- number picker UI 변경 버그 수정
   
## **작업 상세내용**
- AlertDialog에서 Dialog로 변경하여 커스텀다이얼로그로 변경

## **결과 화면**
<img src=https://github.com/BCSDLab/KOIN_ANDROID/assets/128479811/5e2b1bd4-6bfb-407c-9324-d1f6a320ff61 width="200" height="200">
 -> 
<img src=https://github.com/user-attachments/assets/e73e4ccd-90b9-488d-b99d-befb3dfa4b76 width="200" height="200">

2024-10-27 23:46 UTC, yunjaena requested changes
수고했습니다! 커멘트 확인해주세요!

2024-10-27 23:46 UTC, yunjaena commented on business/src/main/java/in/koreatech/business/feature/store/modifyinfo/ModifyInfoViewModel.kt
> +            Log.e("로그 리스트", state.operatingTimeList.toString())
로그 제거 또는 외부에 노출 되지 않게 변경

2024-10-28 15:05 UTC, Jokwanhee approved these changes
고생하셨습니다~ 😎

2024-10-29 02:11 UTC, yunjaena approved these changes
수고하셨습니다!

2024-10-29 02:36 UTC, merged