[Feature]사장님 앱 강제 업데이트
BCSDLab/KOIN_ANDROID pull request #440
Opened 2024-10-29 08:08 UTC by hsgo2430

## **개요**
- 사장님 강제 업데이트 
   
## **작업 상세내용**
- 코인 강제업데이트 기능을 사장님 앱에 이식
    - coil라이브러리를 사용하여 gif 호출

## **결과 화면**
<img src= https://github.com/user-attachments/assets/8d523a25-56b4-466a-a1e8-9f4d557e6d91 width="200" height="400">

강제 업데이트 화면

<img src=  https://github.com/user-attachments/assets/002f1164-2f8c-4311-b3c5-e4f8ae1e5e0e width="200" height="400">

다이얼로그

<img src= https://github.com/user-attachments/assets/2fd4fc1c-20a9-43a7-a4a3-c37cefe06195  width="200" height="400">

작동 사진

2024-10-29 12:55 UTC, Jokwanhee approved these changes
고생하셨습니다!!

2024-10-30 07:03 UTC, nodobi approved these changes
고생하셨습니다!

2024-10-30 10:05 UTC, nayunjae requested changes
커멘트 확인해주세요!

2024-10-30 10:05 UTC, nayunjae commented on business/src/main/java/in/koreatech/business/util/GetGifImage.kt
> +    drawableId: Int,
drawablId 보다는 painterResource로 받는게 좋아보입니다

2024-10-30 10:05 UTC, nayunjae commented on business/src/main/java/in/koreatech/business/util/GetGifImage.kt
> +                size(Size.ORIGINAL)
받아 오는 size가 크면 OOM이 걸릴 수 있기 떄문에 파라미터로 받을 수 있게 변경해주세요.

2024-10-30 11:35 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/util/GetGifImage.kt
> +    drawableId: Int,
인자 명을 painterResource로 변경하였습니다!

2024-10-30 11:35 UTC, hsgo2430 commented on business/src/main/java/in/koreatech/business/util/GetGifImage.kt
> +                size(Size.ORIGINAL)
gif 이미지는 drawable 폴더에 있어서 drawable리소스의 가로 세로를 구하는 함수를 새로 만들고 해당 값을 넘겨주는 방식으로 수정하였습니다!

2024-10-30 13:24 UTC, yunjaena approved these changes
수고하셨습니다 :)

2024-10-30 13:25 UTC, yunjaena commented
conflict해결해주세요!

2024-10-30 13:37 UTC, merged