[Feature] 컴포넌트 추가
BCSDLab/KOIN_ANDROID pull request #444
Opened 2024-10-30 16:34 UTC by ThirFir

## 개요
- designsystem 모듈 내 component 패키지에 컴포넌트 일부 추가
- 버튼, 칩, 탭 레이아웃, 앱 바
- 리플없는 clickable 추가

## 작업 상세
### 버튼
<img width="400" alt="image" src="https://github.com/user-attachments/assets/0f80d30d-5ebe-4b24-b4f4-33bf9ab341da">

### 텍스트 칩 and 텍스트 칩 그룹
<img width="400" alt="image" src="https://github.com/user-attachments/assets/279c621b-ac36-4224-a43a-e82200c05324">

### 기본 탭 레이아웃
<img width="425" alt="image" src="https://github.com/user-attachments/assets/652776e5-fbc7-4ea0-90c4-12a0e60edeb4">

### 기본 앱바
<img width="408" alt="image" src="https://github.com/user-attachments/assets/58d62ff1-f8db-40ad-a35a-0c91b2f45b86">

2024-10-31 01:10 UTC, Jokwanhee approved these changes
고생했어요~ 🙇🏻  noripple 왔다! 👀

2024-10-31 09:27 UTC, kongwoojin requested changes
고생하셨습니다!
코멘트 한번만 확인 부탁드려요 :)

2024-10-31 09:27 UTC, kongwoojin commented on core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/component/text/LeadingIconText.kt
> +            painterResource(id = iconRes),
```
painter = painterResource(id = iconRes)
```
이렇게 고치는게 좋을 것 같습니다!

2024-10-31 09:27 UTC, kongwoojin commented on core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/component/text/LeadingIconText.kt
> +        )
```
        Spacer(modifier = Modifier.width(spacing))
        Text(
            text = text,
            style = textStyle
        )
```
Modifier.padding 대신 Spacer를 써도 좋을 것 같습니다!

2024-10-31 10:02 UTC, ThirFir commented on core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/component/text/LeadingIconText.kt
> +        )
Spacer가 낫겠네요 바꿀게용

2024-10-31 10:02 UTC, ThirFir commented on core/designsystem/src/main/java/in/koreatech/koin/core/designsystem/component/text/LeadingIconText.kt
> +            painterResource(id = iconRes),
꼼꼼하시군요 추가하겠습니다 !

2024-10-31 11:06 UTC, kongwoojin approved these changes
고생하셨습니다!

2024-10-31 11:39 UTC, merged

2024-11-01 05:49 UTC, nodobi commented
조금 늦은 코멘트긴 하지만.. 디자인 시스템에선 일반적으로 더이상 쪼갤 수 없는 단위의 컴포넌트를 atom 이라는 디렉토리로 분류하더라구요.
이 부분은 참고만 해주시고 나중에 디자인 시스템 관련해서 진행되는거 있으면 말씀드리고 분리 진행해보겠습니다!