Feature/add land test case
BCSDLab/KOIN_ANDROID pull request #57
Opened 2020-05-03 09:41 UTC by rekafekili

복덕방 Unit Test 추가하였습니다.

2020-05-15 13:21 UTC, hyerim-p requested changes

2020-05-15 13:21 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/data/network/interactor/LandRestInteractor.java
> +                            apiCallback.onFailure(new Throwable("서버와의 연결이 불안정합니다"));
동일한 상황에 하드코딩 된 부분이 좀 있던데 그부분과 함께 String으로 바꾸는 건 어떤가요?

2020-05-15 13:21 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/data/network/interactor/BokdukRestInteractor.java
> +//
사용하지 않는 파일이면 삭제하는게 더 좋지 않을까요? 아래 LandRestInteractor.java 로 대체한 것 같은데 맞나요?

2020-05-25 10:59 UTC, rekafekili commented on koin/src/main/java/in/koreatech/koin/data/network/interactor/BokdukRestInteractor.java
> +//
넵 맞습니다. Bokduk으로 명명된 Interactor와 Entity를 삭제하도록 하겠습니다.

2020-05-25 11:19 UTC, rekafekili commented on koin/src/main/java/in/koreatech/koin/data/network/interactor/LandRestInteractor.java
> +                            apiCallback.onFailure(new Throwable("서버와의 연결이 불안정합니다"));
Test Case가 모두 병합되는대로 하드 코딩 부분들 한꺼번에 수정해도 될까요??

2020-05-31 15:15 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/data/network/interactor/BokdukRestInteractor.java
> +//
넵 다음 PR때 해당부분 명시해주세요~

2020-05-31 15:16 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/data/network/interactor/LandRestInteractor.java
> +                            apiCallback.onFailure(new Throwable("서버와의 연결이 불안정합니다"));
@rekafekili  넵 다음 PR때 해당 부분 명시해주세요~

2020-05-31 15:16 UTC, merged