Feature/add usedmarket test case
BCSDLab/KOIN_ANDROID pull request #59
Opened 2020-05-04 13:50 UTC by rekafekili

중고장터 Unit Test 추가하였습니다.

2020-05-15 13:23 UTC, hyerim-p requested changes

2020-05-15 13:23 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/ui/usedmarket/presenter/MarketUsedCreatePresenter.java
> +            if(object instanceof Item) {
띄어쓰기 생략

2020-05-15 13:23 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/ui/usedmarket/presenter/MarketUsedCreatePresenter.java
> +            if(object instanceof Item) {
동일하게 띄어쓰기 생략

2020-05-25 11:22 UTC, rekafekili commented on koin/src/main/java/in/koreatech/koin/ui/usedmarket/presenter/MarketUsedCreatePresenter.java
> +            if(object instanceof Item) {
넵 수정하겠습니다

2020-05-25 11:22 UTC, rekafekili commented on koin/src/main/java/in/koreatech/koin/ui/usedmarket/presenter/MarketUsedCreatePresenter.java
> +            if(object instanceof Item) {
넵 수정하겠습니다.

2020-05-31 15:17 UTC, merged