Feature/revise rich editor
BCSDLab/KOIN_ANDROID pull request #8
Opened 2020-01-17 05:50 UTC by rekafekili

- 리치 에디터 기능을 추가하였습니다.

- 이미지 압축 과정으로 인해 발생하는 버그를 고쳤습니다.

2020-01-19 11:11 UTC, hyerim-p requested changes

2020-01-19 11:11 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/service_board/presenters/ArticleEditPresenter.java
> +            if(item.getUrls() != null)
띄어쓰기와 대괄호 빠졌네요

2020-01-19 11:11 UTC, hyerim-p commented on core/src/main/java/in/koreatech/koin/core/bases/BaseNavigationActivity.java
> +        }else if (itemId == R.id.navi_item_myinfo) {
띄어쓰기 빠졌네요

2020-01-19 11:11 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/service_used_market/ui/MarketUsedSellDetailActivity.java
> +        Log.e(TAG, "showGrantCheck: " + isGranted);
남겨둬야할 로그인가요?

2020-01-19 11:11 UTC, hyerim-p commented on core/src/main/java/in/koreatech/koin/core/bases/BaseNavigationActivity.java
> +
여기는 공백이 필요없어보이네요

2020-01-19 11:11 UTC, hyerim-p commented on koin/src/main/res/layout/activity_article_edit.xml
>                              android:hint="제목을 입력해주세요"
익명게시판 글 작성 화면 진입시 입력 포커스가 '내용'이 아니라 '제목'에 가야하는게 맞지 않을까요?

2020-01-19 11:11 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/service_board/ui/ArticleEditActivity.java
> +    public void initEditor() {
에디터가 한 줄 전체에 적용 되던데 부분 적용은 힘들었나요?

2020-01-19 11:11 UTC, hyerim-p commented on core/src/main/java/in/koreatech/koin/core/networks/interactors/MarketUsedRestInteractor.java
> +        RetrofitManager.getInstance().getRetrofit().create(MarketService.class).postThumbanilImage(addAuthorizationBearer(token), filePart)
큰 차이는 없지만 아래코드처럼 .을 나눠서 작성한다면 postThumbanilImage도 아래로 내리는게 가독성이 더 좋아보이네요

2020-01-19 11:11 UTC, hyerim-p commented on core/src/main/java/in/koreatech/koin/core/util/ImageUtil.java
> +            if (quality <= 0) return null;
이런식으로 계속 한 줄에 다 쓰는 것도 가독성이 그리 좋지는 않아요

2020-01-19 11:11 UTC, hyerim-p commented on core/src/main/java/in/koreatech/koin/core/util/ImageUtil.java
> +            Log.d(TAG, "size: " + bitmapdata.length/10000.0);
필요없는 로그는 지워주세요

2020-01-19 11:11 UTC, hyerim-p commented on core/src/main/java/in/koreatech/koin/core/util/ImageUtil.java
> +        }
try 문 하나에 catch를 연결해서 써도 괜찮을 것 같은데 try-catch 2개로 나눈 이유가 있나요?

2020-01-19 11:11 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/service_board/presenters/ArticleEditPresenter.java
> +        marketUsedInteractor.uploadImage(file, uploadImageApiCallback);
큰 건 아니지만 if문 '{'를 하나의 방식으로 통일하는게 더 좋습니다. 그리고 if문 뒤에 띄어쓰기가 빠졌네요

2020-01-19 11:11 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/service_board/ui/KoinRichEditor.java
> +    private OnClickListener cancelClickListener;
어디는 m이 있고 어디는 m이 없네요. m을 없애기로 한거면 앞으로 작성되는 코드에서 만이라도 통일해주세요

2020-01-19 11:11 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/service_board/ui/ArticleEditActivity.java
> +    public void initEditor() {
첫번째 줄에 에디터 적용 후 줄바꿈 시 다음 줄에선 변경된 에디터가 초기화 되던데 의도한건가요?

2020-01-19 11:11 UTC, hyerim-p commented on koin/src/main/java/in/koreatech/koin/service_board/ui/ArticleEditActivity.java
> +    public void initEditor() {
들여쓰기가 한칸만 가능하던데 의도한건가요?

2020-01-21 13:59 UTC, rekafekili commented on koin/src/main/java/in/koreatech/koin/service_board/presenters/ArticleEditPresenter.java
> +            if(item.getUrls() != null)
넵 수정하였습니다.

2020-01-21 13:59 UTC, rekafekili commented on core/src/main/java/in/koreatech/koin/core/bases/BaseNavigationActivity.java
> +        }else if (itemId == R.id.navi_item_myinfo) {
넵 수정하였습니다.

2020-01-21 13:59 UTC, rekafekili commented on koin/src/main/java/in/koreatech/koin/service_used_market/ui/MarketUsedSellDetailActivity.java
> +        Log.e(TAG, "showGrantCheck: " + isGranted);
필요 없을듯하여 지우도록 하겠습니다.

2020-01-21 13:59 UTC, rekafekili commented on core/src/main/java/in/koreatech/koin/core/bases/BaseNavigationActivity.java
> +
넵 공백 지우겠습니다.

2020-01-21 14:01 UTC, rekafekili commented on core/src/main/java/in/koreatech/koin/core/networks/interactors/MarketUsedRestInteractor.java
> +        RetrofitManager.getInstance().getRetrofit().create(MarketService.class).postThumbanilImage(addAuthorizationBearer(token), filePart)
넵 내리겠습니다.

2020-01-21 14:01 UTC, rekafekili commented on core/src/main/java/in/koreatech/koin/core/util/ImageUtil.java
> +            if (quality <= 0) return null;
넵 수정하겠습니다.

2020-01-21 14:01 UTC, rekafekili commented on core/src/main/java/in/koreatech/koin/core/util/ImageUtil.java
> +            Log.d(TAG, "size: " + bitmapdata.length/10000.0);
넵 지우겠습니다.

2020-01-21 14:02 UTC, rekafekili commented on core/src/main/java/in/koreatech/koin/core/util/ImageUtil.java
> +        }
빠르게 수정하려던 중에 지나쳐버렸던 것 같습니다. 하나로 합치도록 하겠습니다.

2020-01-21 14:02 UTC, rekafekili commented on koin/src/main/java/in/koreatech/koin/service_board/presenters/ArticleEditPresenter.java
> +        marketUsedInteractor.uploadImage(file, uploadImageApiCallback);
넵 수정하겠습니다.

2020-01-21 14:03 UTC, rekafekili commented on koin/src/main/java/in/koreatech/koin/service_board/ui/KoinRichEditor.java
> +    private OnClickListener cancelClickListener;
넵 수정하겠습니다.

2020-01-21 14:07 UTC, rekafekili commented on koin/src/main/res/layout/activity_article_edit.xml
>                              android:hint="제목을 입력해주세요"
넵 제목으로 가는게 맞습니다. 수정하도록 하겠습니다.

2020-01-26 11:47 UTC, hyerim-p approved these changes

2020-01-26 11:48 UTC, merged